/* C application - generated by Brief */
/* Target: main */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>


typedef struct {
    double x1;
    double x2;
    double y1;
    double y2;
    int32_t count;
} State;

static State *state = NULL;

void state_init(void) {
    state->x1 = 0.0;
    state->x2 = 0.0;
    state->y1 = 0.0;
    state->y2 = 0.0;
    state->count = 0;
}

/* Guard dirty flags for pre-computation caching */
static bool process_dirty = true;

bool process(void) {
    if (!process_dirty) {
        return true;
    }
    process_dirty = false;

    /* pre: Lt(Identifier("count"), Identifier("total")) */
    int32_t f0 = (0.003916126444 * 1);
    int32_t f1 = (0.007832252889 * state->x1);
    int32_t f2 = (0.003916126444 * state->x2);
    int32_t ff = ((f0 + f1) + f2);
    int32_t fb1 = (-1.8153410827 * state->y1);
    int32_t fb2 = (0.8310055893 * state->y2);
    int32_t fb = (fb1 + fb2);
    int32_t out = (ff - fb);
    state->x2 = state->x1;
    state->x1 = 1;
    state->y2 = state->y1;
    state->y1 = out;
    state->count = (state->count + 1);
    process_dirty = true;
    /* post: Eq(Identifier("count"), Identifier("total")) */
    return true;
}

static void init_wrapper(void) {
    state = (State *)malloc(sizeof(State));
    state_init();
}

int main(void) {
    init_wrapper();
    return 0;
}
