/* C application - generated by Briv */
/* Target: main */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>


/* FFI Function Declarations */

/* Constant Definitions */
#define N 50000000
#define print_interval 100000
extern bool __print_int(int32_t n);

typedef struct {
    int32_t ops;
} State;

static State *state = NULL;

void state_init(void) {
    state->ops = 0;
}

/* Guard dirty flags for pre-computation caching */
static bool work_dirty = true;

bool work(void) {
    if (!work_dirty) {
        return true;
    }
    work_dirty = false;

    /* pre: And(Identifier("io_pending"), Lt(Identifier("ops"), Identifier("N"))) */
    state->ops = (state->ops + 1);
    work_dirty = true;
    if ((0 /* expr not implemented */ == 0)) {
    /* FFI call to __print_int with error handling */
    bool _result___print_int = __print_int(state->ops);
    if ((_result___print_int >= -1 && _result___print_int <= -1)) goto ffi_error___print_int;
    goto ffi_ok___print_int;
ffi_error___print_int:
    /* FFI error occurred for __print_int */
ffi_ok___print_int:
    }
    /* transaction complete */
    /* post: Eq(Identifier("ops"), Identifier("N")) */
    return true;
}

static void init_wrapper(void) {
    state = (State *)malloc(sizeof(State));
    state_init();
}

int main(void) {
    init_wrapper();
    return 0;
}
