/* C application - generated by Brief */
/* Target: main */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>


static void init_wrapper(void) {
}

int main(void) {
    return 0;
}
