/* C application - generated by Brief */
/* Target: main */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>


typedef struct {
    int32_t x;
} State;

static State *state = NULL;

void state_init(void) {
    state->x = 0;
}

static void init_wrapper(void) {
    state = (State *)malloc(sizeof(State));
    state_init();
}

int main(void) {
    init_wrapper();
    return 0;
}
