/* C application - generated by Brief */
/* Target: Hosted (Desktop/Embedded Linux) */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

void init_wrapper(void) {
}

int main(void) {
    return 0;
}
