/* C application - generated by Brief */
/* Target: module_init */

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/kthread.h>
#include <linux/delay.h>



/* Module parameters */
static int test_mode = 1;
module_param(test_mode, int, 0644);
MODULE_PARM_DESC(test_mode, "1=stub mode (safe), 0=real hardware (DANGER)");

typedef struct {
    int32_t val;
} State;

static State state_instance;
static State *state = &state_instance;

void state_init(void) {
    state->val = 0;
}

bool Test.init(void) {    /* pre: Bool(true) */
    state->val = 1;
    /* transaction complete */
    /* post: Eq(PriorState("val"), Integer(0)) */
    return true;
}

static void init_wrapper(void) {
    // Static allocation from spec
    state_init();
}


// Kernel module entry points
static int __init brief_init(void) {
    Test.init();
    return 0;
}
module_init(brief_init);

static void __exit brief_exit(void) {
    Test.init();
}
module_exit(brief_exit);

MODULE_DESCRIPTION("Generated by Brief");
MODULE_LICENSE("GPL");
