/* C application - generated by Brief */
/* Target: Hosted (Desktop/Embedded Linux) */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>

typedef struct {
    uint32_t gpu_dev;
    uint32_t gpu_bar_addr;
    bool gpu_mapped;
    bool dma_active;
    uint32_t current_layer;
} State;

static State *state = NULL;

void state_init(void) {
    state->gpu_dev = 0;
    state->gpu_bar_addr = 0;
    state->gpu_mapped = false;
    state->dma_active = false;
    state->current_layer = 0;
}

bool init(void) {
    /* pre: Eq(Identifier("gpu_mapped"), Bool(false)) */
    0 /* expr not implemented */;
    int32_t result = 0 /* expr not implemented */;
    /* statement not implemented */
    /* statement not implemented */
    /* transaction complete */
    /* post: Eq(Identifier("gpu_mapped"), Bool(true)) */
    return true;
}

bool calc_layer(void) {
    /* pre: And(Not(Identifier("dma_active")), Lt(Identifier("current_layer"), Identifier("MAX_LAYERS"))) */
    state->current_layer = (state->current_layer + 1);
    /* transaction complete */
    /* post: Eq(Identifier("current_layer"), Add(PriorState("current_layer"), Integer(1))) */
    return true;
}

bool stream_layer(void) {
    /* pre: And(Not(Identifier("dma_active")), Lt(Identifier("current_layer"), Identifier("MAX_LAYERS"))) */
    state->dma_active = true;
    /* transaction complete */
    /* post: Eq(Identifier("dma_active"), Bool(true)) */
    return true;
}

bool dma_done(void) {
    /* pre: Eq(Identifier("dma_active"), Bool(true)) */
    state->dma_active = false;
    /* transaction complete */
    /* post: Eq(Identifier("dma_active"), Bool(false)) */
    return true;
}

bool cleanup(void) {
    /* pre: Eq(Identifier("gpu_mapped"), Bool(true)) */
    /* statement not implemented */
    /* statement not implemented */
    0 /* expr not implemented */;
    state->gpu_mapped = false;
    /* transaction complete */
    /* post: Eq(Identifier("gpu_mapped"), Bool(false)) */
    return true;
}

void init_wrapper(void) {
    state = (State *)malloc(sizeof(State));
    state_init();
}

int main(void) {
    init_wrapper();
    return 0;
}
