// Generated by briev-compiler CIRCT backend
// Run: circt-opt program.mlir | circt-translate --export-verilog

hw.module @top(in %clock: !seq.clock, in %reset: i1, out halt: i1, out counter: i64) {
  %chalt_init_0 = hw.constant 0 : i1
  %ccounter_init_1 = hw.constant 0 : i64
  %true = hw.constant true
  %false = hw.constant false
  %cint_2 = hw.constant 255 : i64
  %step_pre_0 = comb.icmp ult %ccounter_init_1, %cint_2 : i64
  sv.assert %step_pre_0, immediate message "pre: step"
  %cint_3 = hw.constant 255 : i64
  %step_post_1 = comb.icmp ult %ccounter_init_1, %cint_3 : i64
  sv.assert %step_post_1, immediate message "post: step"
  %cint_4 = hw.constant 1 : i64
  %bin_2 = comb.add %ccounter_init_1, %cint_4 : i64
  %counter_next_3 = comb.mux %true, %bin_2, %ccounter_init_1 : i64
  %halt_next_4 = comb.mux %reset, %chalt_init_0, %chalt_init_0 : i1
  %halt_0 = seq.firreg %halt_next_4 clock %clock preset 0 : i1
  %counter_next_5 = comb.mux %reset, %ccounter_init_1, %counter_next_3 : i64
  %counter_1 = seq.firreg %counter_next_5 clock %clock preset 0 : i64
  hw.output %halt_0, %counter_1 : i1, i64
