// Native Rust application - generated by Briv
// Target: main

use std::collections::HashMap;

#[derive(Debug, Clone)]
pub struct State {
    pub counter: i32,
}

impl Default for State {
    fn default() -> Self {
        Self {
            counter: 0,
        }
    }
}

impl State {
    pub fn increment(&mut self) -> bool {
        // pre: Lt(Identifier("counter"), Integer(10))
        self.counter = (self.counter + 1);
        // transaction complete
        // post: Eq(Identifier("counter"), Add(PriorState("counter"), Integer(1)))
        true
    }

}

fn main() {
    println!("Briv kernel starting\n");
    let mut state = State::default();
    state.increment();
    println!("Briv kernel done\n");
}
