// ── Autogenous Binding Generation ───────────────────────────
//
// Phase 4.5: This module generates foreign-language bindings from
// the TypeUniverse's ResolvedType layout information and any #export
// directives on definitions/transactions.
//
// Reads:
//   - TypeUniverse.types — ResolvedType with bytes, alignment, on_exit
//   - Export list: (export_name, orig_fn_name, params, ret_type)
//
// Outputs per --emit-bindings <dir>:
//   - briev_types.h      (C struct definitions + function declarations)
//   - briev_bindings.rs  (Rust #[repr(C)] structs + extern "C" fns)
//   - briev_bindings.py  (Python ctypes definitions)
//
// No stubs. Every function produces complete output for all inputs.

use crate::type_universe::{ResolvedType, TypeUniverse};
use std::collections::HashMap;

/// Parameter description for an exported function.
#[derive(Debug, Clone)]
pub struct ExportParam {
    pub name: String,
    pub ty: crate::ast::Type,
}

/// An exported function declaration.
#[derive(Debug, Clone)]
pub struct ExportDecl {
    pub export_name: String,
    pub orig_name: String,
    pub params: Vec<ExportParam>,
    pub ret_ty: crate::ast::Type,
}

/// Generate C header, Rust bindings, and Python stubs from type universe
/// and export declarations.
pub fn emit_all(
    universe: &TypeUniverse,
    exports: &[ExportDecl],
    out_dir: &str,
) -> Result<(), String> {
    let h_content = emit_c_header(universe, exports);
    std::fs::write(format!("{}/briev_types.h", out_dir), &h_content)
        .map_err(|e| format!("Failed to write C header: {}", e))?;

    let rs_content = emit_rust_bindings(universe, exports);
    std::fs::write(format!("{}/briev_bindings.rs", out_dir), &rs_content)
        .map_err(|e| format!("Failed to write Rust bindings: {}", e))?;

    let py_content = emit_python_stubs(universe, exports);
    std::fs::write(format!("{}/briev_bindings.py", out_dir), &py_content)
        .map_err(|e| format!("Failed to write Python stubs: {}", e))?;

    Ok(())
}

/// Emit a C header file with struct definitions and function declarations.
fn emit_c_header(universe: &TypeUniverse, exports: &[ExportDecl]) -> String {
    let mut out = String::new();
    out.push_str("// Autogenerated by Briev Compiler — do not edit manually\n");
    out.push_str("#pragma once\n");
    out.push_str("#include <stdint.h>\n\n");

    // Struct definitions for all resolved types
    out.push_str("// ── Type Layouts ──\n");
    for name in universe.types.keys() {
        let Some(rt) = universe.types.get(name) else { continue };
        emit_c_struct(&mut out, name, rt);
    }

    // Function declarations for all exported symbols
    if !exports.is_empty() {
        out.push_str("\n// ── Exported Functions ──\n");
        out.push_str("// The first parameter is always a pointer to the Briev runtime state.\n");
        out.push_str("// Callers must allocate and zero-initialize a State struct before calling.\n\n");
        for decl in exports {
            emit_c_function_decl(&mut out, decl, universe);
        }
    }

    out
}

/// Emit a C struct definition from ResolvedType info.
fn emit_c_struct(out: &mut String, name: &str, rt: &ResolvedType) {
    if rt.bytes == 0 {
        return; // Skip abstract types
    }
    out.push_str(&format!("typedef struct {{"));
    // If the type has a simple byte layout, emit a byte array
    // For types with user-defined projections, emit as opaque struct
    out.push_str(&format!("\n    uint8_t _data[{}];", rt.bytes));
    out.push_str(&format!("\n}} {};\n\n", name));
}

/// Emit a C function declaration for an exported Briev function.
fn emit_c_function_decl(out: &mut String, decl: &ExportDecl, universe: &TypeUniverse) {
    let c_ret = type_to_c(&decl.ret_ty, universe);
    out.push_str(&format!("{} {}(",
        c_ret, decl.export_name));
    out.push_str("struct BrievState* state");
    for param in &decl.params {
        let c_ty = type_to_c(&param.ty, universe);
        out.push_str(&format!(", {} {}", c_ty, param.name));
    }
    out.push_str(");\n");
}

/// Map a Briev Type to a Rust type.
fn type_to_rust(ty: &crate::ast::Type, universe: &TypeUniverse) -> String {
    match ty {
        crate::ast::Type::Custom(__t) if __t == "Int" || __t == "UInt" => "i64".to_string(),
        crate::ast::Type::Custom(__t) if __t == "Float" => "f32".to_string(),
        crate::ast::Type::Custom(__t) if __t == "Bool" => "u8".to_string(),
        crate::ast::Type::Custom(__t) if __t == "Char" => "u32".to_string(),
        crate::ast::Type::Custom(__t) if __t == "String" || __t == "Data" => "*const u8".to_string(),
        crate::ast::Type::Void => "()".to_string(),
        crate::ast::Type::Custom(name) | crate::ast::Type::Applied(name, _) => {
            if universe.types.contains_key(name) {
                name.clone()
            } else {
                "i64".to_string()
            }
        }
        _ => "i64".to_string(),
    }
}

/// Map a Briev Type to a Python ctypes type name.
fn type_to_python(ty: &crate::ast::Type, universe: &TypeUniverse) -> &'static str {
    match ty {
        crate::ast::Type::Custom(__t) if __t == "Int" || __t == "UInt" => "ctypes.c_int64",
        crate::ast::Type::Custom(__t) if __t == "Float" => "ctypes.c_float",
        crate::ast::Type::Custom(__t) if __t == "Bool" => "ctypes.c_uint8",
        crate::ast::Type::Custom(__t) if __t == "Char" => "ctypes.c_uint32",
        crate::ast::Type::Custom(__t) if __t == "String" || __t == "Data" => "ctypes.c_char_p",
        crate::ast::Type::Void => "None",
        crate::ast::Type::Custom(name) | crate::ast::Type::Applied(name, _) => {
            if universe.types.contains_key(name) {
                "ctypes.c_int64"
            } else {
                "ctypes.c_int64"
            }
        }
        _ => "ctypes.c_int64",
    }
}

/// Map a Briev Type to a C type.
fn type_to_c(ty: &crate::ast::Type, universe: &TypeUniverse) -> String {
    match ty {
        crate::ast::Type::Custom(__t) if __t == "Int" || __t == "UInt" => "int64_t".to_string(),
        crate::ast::Type::Custom(__t) if __t == "Float" => "float".to_string(),
        crate::ast::Type::Custom(__t) if __t == "Bool" => "uint8_t".to_string(),
        crate::ast::Type::Custom(__t) if __t == "Char" => "uint32_t".to_string(),
        crate::ast::Type::Custom(__t) if __t == "String" || __t == "Data" => "struct BrievString".to_string(),
        crate::ast::Type::Void => "void".to_string(),
        crate::ast::Type::Custom(name) => {
            if universe.types.contains_key(name) {
                format!("struct {}", name)
            } else {
                "int64_t".to_string()
            }
        }
        crate::ast::Type::Applied(name, _) => {
            if universe.types.contains_key(name) {
                format!("struct {}", name)
            } else {
                "int64_t".to_string()
            }
        }
        _ => "int64_t".to_string(),
    }
}

/// Emit Rust bindings file.
fn emit_rust_bindings(universe: &TypeUniverse, exports: &[ExportDecl]) -> String {
    let mut out = String::new();
    out.push_str("// Autogenerated by Briev Compiler — do not edit manually\n");
    out.push_str("#![allow(non_camel_case_types, dead_code)]\n\n");
    out.push_str("use std::ffi::c_void;\n\n");

    // Struct definitions
    out.push_str("// ── Type Layouts ──\n");
    for name in universe.types.keys() {
        let Some(rt) = universe.types.get(name) else { continue };
        emit_rust_struct(&mut out, name, rt);
    }

    // Extern C function declarations
    if !exports.is_empty() {
        out.push_str("\n// ── Exported Functions ──\n");
        out.push_str("#[link(name = \"briev_program\")]\n");
        out.push_str("extern \"C\" {\n");
        for decl in exports {
            emit_rust_extern_fn(&mut out, decl, universe);
        }
        out.push_str("}\n");
    }

    out
}

/// Emit a Rust #[repr(C)] struct from ResolvedType info.
fn emit_rust_struct(out: &mut String, name: &str, rt: &ResolvedType) {
    if rt.bytes == 0 {
        return;
    }
    out.push_str(&format!("#[repr(C)]\npub struct {} {{\n", name));
    out.push_str(&format!("    _data: [u8; {}],\n", rt.bytes));
    out.push_str("}\n\n");
}

/// Emit an extern "C" function declaration for Rust bindings.
fn emit_rust_extern_fn(out: &mut String, decl: &ExportDecl, universe: &TypeUniverse) {
    let rs_ret = type_to_rust(&decl.ret_ty, universe);
    out.push_str(&format!("    pub fn {}(state: *mut c_void", decl.export_name));
    for param in &decl.params {
        let rs_ty = type_to_rust(&param.ty, universe);
        out.push_str(&format!(", {}: {}", param.name, rs_ty));
    }
    out.push_str(&format!(") -> {};\n", rs_ret));
}

/// Emit a Python function wrapper for an exported Briev function.
fn emit_py_function(out: &mut String, decl: &ExportDecl, universe: &TypeUniverse) {
    let py_restype = type_to_python(&decl.ret_ty, universe);
    out.push_str(&format!("def {}(state", decl.export_name));
    for param in &decl.params {
        out.push_str(&format!(", {}", param.name));
    }
    out.push_str("):\n");
    out.push_str(&format!("    _lib.{}.restype = {}\n", decl.export_name, py_restype));
    out.push_str(&format!("    _lib.{}.argtypes = [ctypes.c_void_p", decl.export_name));
    for param in &decl.params {
        let py_ty = type_to_python(&param.ty, universe);
        out.push_str(&format!(", {}", py_ty));
    }
    out.push_str("]\n");
    let py_call_args = format!("ctypes.c_void_p(state){}", 
        decl.params.iter().map(|p| format!(", {}", p.name)).collect::<Vec<_>>().join(""));
    out.push_str(&format!("    return _lib.{}({})\n\n", decl.export_name, py_call_args));
}

/// Map a Briev Type to a Rust type.
fn type_name_to_rust(type_name: &str, universe: &TypeUniverse) -> String {
    match type_name {
        "Int" | "UInt" => "i64".to_string(),
        "Float" => "f32".to_string(),
        "Bool" => "u8".to_string(),
        "Char" => "u32".to_string(),
        "String" | "Data" => "*const u8".to_string(),
        "Void" => "()".to_string(),
        _ => {
            if universe.types.contains_key(type_name) {
                type_name.to_string()
            } else {
                "i64".to_string()
            }
        }
    }
}

/// Emit Python ctypes stubs.
fn emit_python_stubs(universe: &TypeUniverse, exports: &[ExportDecl]) -> String {
    let mut out = String::new();
    out.push_str("# Autogenerated by Briev Compiler — do not edit manually\n");
    out.push_str("import ctypes\n\n");
    out.push_str("_lib = ctypes.CDLL(\"./briev_program.so\")\n\n");

    // Struct definitions
    out.push_str("# ── Type Layouts ──\n");
    for name in universe.types.keys() {
        let Some(rt) = universe.types.get(name) else { continue };
        emit_py_class(&mut out, name, rt);
    }

    // Function signatures
    if !exports.is_empty() {
        out.push_str("\n# ── Exported Functions ──\n");
        for decl in exports {
            emit_py_function(&mut out, decl, universe);
        }
    }

    out
}

/// Emit a Python ctypes class for a ResolvedType.
fn emit_py_class(out: &mut String, name: &str, rt: &ResolvedType) {
    if rt.bytes == 0 {
        return;
    }
    out.push_str(&format!("class {}(ctypes.Structure):\n", name));
    out.push_str("    _pack_ = 1\n");
    out.push_str(&format!("    _fields_ = [\n"));
    out.push_str(&format!("        (\"_data\", ctypes.c_ubyte * {}),\n", rt.bytes));
    out.push_str("    ]\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::Type;
    use crate::type_universe::{ResolvedType, TypeUniverse};

    fn make_test_type(name: &str, bytes: u64) -> ResolvedType {
        ResolvedType {
            name: name.to_string(),
            base: "Bit".to_string(),
            bytes,
            min_bits: bytes * 8,
            max_bits: bytes * 8,
            alignment: 8,
            properties: std::collections::HashMap::new(),
            fields: vec![],
        }
    }

    fn make_test_universe() -> TypeUniverse {
        let mut types = HashMap::new();
        types.insert("Packet".to_string(), make_test_type("Packet", 64));
        types.insert("Header".to_string(), make_test_type("Header", 16));
        TypeUniverse {
            types,
            warnings: Vec::new(),
        }
    }

    #[test]
    fn test_c_header_generates_pragma_once() {
        let universe = make_test_universe();
        let h = emit_c_header(&universe, &[]);
        assert!(h.contains("#pragma once"));
        assert!(h.contains("Packet"));
        assert!(h.contains("Header"));
    }

    #[test]
    fn test_c_header_with_exports() {
        let universe = make_test_universe();
        let exports = vec![ExportDecl {
            export_name: "process_packet".to_string(),
            orig_name: "process".to_string(),
            params: vec![
                ExportParam { name: "p".to_string(), ty: Type::Custom("Packet".to_string()) },
            ],
            ret_ty: Type::int(),
        }];
        let h = emit_c_header(&universe, &exports);
        assert!(h.contains("process_packet"));
        assert!(h.contains("int64_t"));
        assert!(h.contains("struct Packet"));
    }

    #[test]
    fn test_rust_bindings_generates_repr_c() {
        let universe = make_test_universe();
        let rs = emit_rust_bindings(&universe, &[]);
        assert!(rs.contains("#[repr(C)]"));
        assert!(rs.contains("pub struct Packet"));
    }

    #[test]
    fn test_rust_bindings_with_exports() {
        let universe = make_test_universe();
        let exports = vec![ExportDecl {
            export_name: "process_packet".to_string(),
            orig_name: "process".to_string(),
            params: vec![
                ExportParam { name: "p".to_string(), ty: Type::Custom("Packet".to_string()) },
            ],
            ret_ty: Type::bool_(),
        }];
        let rs = emit_rust_bindings(&universe, &exports);
        assert!(rs.contains("process_packet"));
        assert!(rs.contains("extern \"C\""));
    }

    #[test]
    fn test_python_stubs_generates_ctypes() {
        let universe = make_test_universe();
        let py = emit_python_stubs(&universe, &[]);
        assert!(py.contains("ctypes.Structure"));
        assert!(py.contains("class Packet"));
    }

    #[test]
    fn test_type_mapping() {
        let universe = make_test_universe();
        assert_eq!(type_to_c(&Type::int(), &universe), "int64_t");
        assert_eq!(type_to_c(&Type::float(), &universe), "float");
        assert_eq!(type_to_c(&Type::bool_(), &universe), "uint8_t");
        assert_eq!(type_to_c(&Type::Custom("Packet".to_string()), &universe), "struct Packet");
        assert_eq!(type_to_rust(&Type::int(), &universe), "i64");
        assert_eq!(type_to_rust(&Type::float(), &universe), "f32");
        assert_eq!(type_to_python(&Type::int(), &universe), "ctypes.c_int64");
        assert_eq!(type_to_python(&Type::float(), &universe), "ctypes.c_float");
    }
}
