// Copyright 2026 Randy Smits-Schreuder Goedheijt
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::ast::{Expr, LinkRef, Program, Statement, TopLevel, Type, ForeignBinding, ForeignSignature, FfiState};
use crate::ffi::error::{ErrorConventions, generate_bounds_check, generate_null_check};  // NEW
use crate::linkage::LinkageConfig;

pub struct CBackend {
    linkage: Option<LinkageConfig>,
    hw_register_names: Vec<String>,
    bare_metal: bool,
    kernel_mode: bool,              // NEW: kernel module target
    kernel_os: Option<String>,     // NEW: "linux", "windows", etc.
    ffi_bindings: Vec<(String, ForeignSignature)>, // NEW: FFI function signatures
    ffi_state: Option<FfiState>,   // NEW: FFI configuration from #![ffi...]
    error_conventions: ErrorConventions,  // NEW: Error handling conventions
    constants: Vec<(String, String)>,  // NEW: const name -> C value
    local_vars: Vec<String>,  // Local variables in current function
    test_mode: bool,  // Generate stub FFI implementations
}

impl CBackend {
    pub fn new() -> Self {
        Self {
            linkage: None,
            hw_register_names: Vec::new(),
            bare_metal: false,
            kernel_mode: false,
            kernel_os: None,
            ffi_bindings: Vec::new(),
            ffi_state: None,
            error_conventions: ErrorConventions::default(),
            constants: Vec::new(),
            local_vars: Vec::new(),
            test_mode: false,
        }
    }

    pub fn with_test_mode(mut self, test_mode: bool) -> Self {
        self.test_mode = test_mode;
        self
    }

    pub fn with_linkage(mut self, linkage: LinkageConfig) -> Self {
        self.linkage = Some(linkage);
        self
    }

    pub fn bare_metal(mut self, bare_metal: bool) -> Self {
        self.bare_metal = bare_metal;
        self
    }

    pub fn with_kernel_mode(mut self, os: Option<String>) -> Self {
        self.kernel_mode = true;
        self.kernel_os = os;
        self
    }

    pub fn generate(&mut self, program: &Program, stem: &str) -> (String, Option<String>) {
        // Collect hardware register names first
        self.collect_hw_registers(program);

        // Collect FFI bindings and state
        self.collect_ffi_bindings(program);

        // Collect constants for #define
        self.collect_constants(program);

        let mut output = String::new();
        let mut makefile = String::new();

        output.push_str("/* C application - generated by Brief */\n");
        if self.kernel_mode {
            output.push_str("/* Target: Kernel Module */\n\n");
        } else if self.bare_metal {
            output.push_str("/* Target: Bare-metal ARM (Cortex-A) */\n\n");
        } else {
            output.push_str("/* Target: Hosted (Desktop/Embedded Linux) */\n\n");
        }

        // Include headers based on mode
        if self.kernel_mode {
            // Kernel mode: include kernel headers (only once!)
            if let Some(os) = &self.kernel_os {
                match os.as_str() {
                    "linux" => {
                        output.push_str("#include <linux/module.h>\n");
                        output.push_str("#include <linux/kernel.h>\n");
                        output.push_str("#include <linux/kthread.h>\n");
                        output.push_str("#include <linux/delay.h>\n");
                    }
                    _ => {
                        // Default kernel headers for unknown OS
                        output.push_str("#include <linux/module.h>\n");
                        output.push_str("#include <linux/kernel.h>\n");
                        output.push_str("#include <linux/kthread.h>\n");
                        output.push_str("#include <linux/delay.h>\n");
                    }
                }
            } else {
                // No OS specified - use defaults
                output.push_str("#include <linux/module.h>\n");
                output.push_str("#include <linux/kernel.h>\n");
                output.push_str("#include <linux/kthread.h>\n");
                output.push_str("#include <linux/delay.h>\n");
            }
        } else {
            output.push_str("#include <stdint.h>\n");
            output.push_str("#include <stdbool.h>\n");
            output.push_str("#include <stddef.h>\n");
        }
        if !self.bare_metal && !self.kernel_mode {
            output.push_str("#include <stdlib.h>\n");
        }
        output.push_str("\n");

        // Generate MMIO definitions from @ link references
        self.generate_linkage_defines(&mut output);

        // Generate FFI function declarations
        self.generate_ffi_declarations(&mut output);

        // Generate module parameters for test mode
        if self.kernel_mode {
            output.push_str("\n/* Module parameters */\n");
            output.push_str("static int test_mode = 1;\n");
            output.push_str("module_param(test_mode, int, 0644);\n");
            output.push_str("MODULE_PARM_DESC(test_mode, \"1=stub mode (safe), 0=real hardware (DANGER)\");\n");
            output.push_str("\n");
        }

        let state_decls = self.collect_state_declarations(program);

        // Only generate struct for non-hardware state
        if !state_decls.is_empty() {
            output.push_str("typedef struct {\n");
            for (name, ty) in &state_decls {
                let c_type = Self::get_c_type(ty);
                output.push_str(&format!("    {} {};\n", c_type, Self::sanitize_name(name)));
            }
            output.push_str("} State;\n\n");

            if self.bare_metal {
                // Static allocation for bare-metal (no malloc)
                output.push_str("static State state_instance;\n");
                output.push_str("static State *state = &state_instance;\n\n");
            } else if self.kernel_mode {
                // Static allocation for kernel (no malloc in kernel space)
                output.push_str("static State state_instance;\n");
                output.push_str("static State *state = &state_instance;\n\n");
            } else {
                // Dynamic allocation for hosted (desktop/embedded Linux)
                output.push_str("static State *state = NULL;\n\n");
            }

            output.push_str("void state_init(void) {\n");
            for (name, ty) in &state_decls {
                let default_val = Self::get_default_value(ty);
                output.push_str(&format!("    state->{} = {};\n", Self::sanitize_name(name), default_val));
            }
            output.push_str("}\n\n");
        }

self.clear_local_vars();

        for (_, txn) in self.collect_transactions(program) {
            self.clear_local_vars();
            output.push_str(&format!(
                "bool {}(void) {{",
                Self::sanitize_name(&txn.name)
            ));
            output.push_str(&format!(
                "    /* pre: {:?} */\n",
                txn.contract.pre_condition
            ));

            for stmt in &txn.body {
                self.statement_to_c(&mut output, stmt);
            }

            output.push_str(&format!(
                "    /* post: {:?} */\n",
                txn.contract.post_condition
            ));
            output.push_str("    return true;\n");
            output.push_str("}\n\n");
        }

        output.push_str("static void init_wrapper(void) {\n");
        let state_decls = self.collect_state_declarations(program);
        if !state_decls.is_empty() {
            if self.bare_metal || self.kernel_mode {
                output.push_str("    // Static allocation for bare-metal/kernel\n");
                output.push_str("    state_init();\n");
            } else {
                output.push_str("    state = (State *)malloc(sizeof(State));\n");
                output.push_str("    state_init();\n");
            }
        }
        output.push_str("}\n\n");

        // Generate appropriate entry point based on mode
        if self.kernel_mode {
            // Kernel module: generate module_init/module_exit
            output.push_str("\n// Kernel module entry points\n");
            
            // Find first transaction that fires (entry point)
            let entry_txn = self.find_entry_point(program);
            
            // Generate module_init
            output.push_str("static int __init brief_init(void) {\n");
            if let Some(entry_name) = entry_txn {
                output.push_str(&format!("    {}();\n", Self::sanitize_name(&entry_name)));
            }
            output.push_str("    return 0;\n");
            output.push_str("}\n");
            output.push_str("module_init(brief_init);\n\n");
            
            // Generate module_exit (look for "exit" transaction)
            let exit_txn = self.find_exit_point(program);
            output.push_str("static void __exit brief_exit(void) {\n");
            if let Some(exit_name) = exit_txn {
                output.push_str(&format!("    {}();\n", Self::sanitize_name(&exit_name)));
            }
            output.push_str("}\n");
            output.push_str("module_exit(brief_exit);\n\n");
            
            // MODULE_DESCRIPTION
            output.push_str("MODULE_DESCRIPTION(\"VITRIOL: Direct NVMe to GPU Streamer for Infinite VRAM\");\n");
            
            // MODULE_LICENSE
            output.push_str("MODULE_LICENSE(\"GPL\");\n");
        } else if self.bare_metal {
            // Bare-metal: generate _start entry point + main
            // Stack at top of 256MB region (grows down)
            output.push_str("/* Bare-metal entry point */\n");
            output.push_str("#define STACK_TOP 0x0F800000\n\n");
            output.push_str("void _start(void) __attribute__((section(\".text.start\")));\n");
            output.push_str("void _start(void) {\n");
            output.push_str("    __asm__ volatile (\n");
            output.push_str("        \"mov sp, %0\\n\"\n");
            output.push_str("        \"bl main\\n\"\n");
            output.push_str("        :\n");
            output.push_str("        : \"r\" (STACK_TOP)\n");
            output.push_str("        : \"memory\"\n");
            output.push_str("    );\n");
            output.push_str("    while(1) { __asm__ volatile(\"wfi\"); }\n");
            output.push_str("}\n\n");

            // Generate main() 
            output.push_str("int main(void) {\n");
            let state_decls = self.collect_state_declarations(program);
            if !state_decls.is_empty() {
                output.push_str("    init_wrapper();\n");
            }
            output.push_str("    return 0;\n");
            output.push_str("}\n");
        } else {
            // Normal/embedded: generate main()
            output.push_str("int main(void) {\n");
            let state_decls = self.collect_state_declarations(program);
            if !state_decls.is_empty() {
                output.push_str("    init_wrapper();\n");
            }
            output.push_str("    return 0;\n");
            output.push_str("}\n");
        }

        // Generate Makefile for kernel modules
        let makefile = if self.kernel_mode {
            Some(self.generate_makefile(stem))
        } else {
            None
        };

        (output, makefile)
    }

    fn find_entry_point(&self, program: &Program) -> Option<String> {
        // First, look for a transaction named "init"
        for item in &program.items {
            if let TopLevel::Transaction(txn) = item {
                if txn.name == "init" {
                    return Some(txn.name.clone());
                }
            }
        }
        
        // Next, look for a transaction with precondition = true
        for item in &program.items {
            if let TopLevel::Transaction(txn) = item {
                // Check if precondition is true (simplified check)
                if let Expr::Bool(true) = txn.contract.pre_condition {
                    return Some(txn.name.clone());
                }
            }
        }
        None
    }

    fn find_exit_point(&self, program: &Program) -> Option<String> {
        // Look for transaction named "exit" or last non-rct transaction
        let mut last_txn = None;
        for item in &program.items {
            if let TopLevel::Transaction(txn) = item {
                if txn.name == "exit" {
                    return Some(txn.name.clone());
                }
                if !txn.is_reactive && !txn.is_async {
                    last_txn = Some(txn.name.clone());
                }
            }
        }
        last_txn
    }

    fn generate_makefile(&self, stem: &str) -> String {
        let mut makefile = String::new();
        makefile.push_str("# Auto-generated Makefile for kernel module\n");
        makefile.push_str(&format!("obj-m += {}.o\n", stem));
        // Note: -objs line not needed for single source file (causes circular dependency)
        makefile.push_str("\n");
        makefile.push_str("all:\n");
        makefile.push_str("\tmake -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules\n\n");
        makefile.push_str("clean:\n");
        makefile.push_str("\tmake -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean\n");
        makefile
    }

    fn collect_hw_registers(&mut self, program: &Program) {
        self.hw_register_names.clear();
        for item in &program.items {
            if let TopLevel::Trigger(trg) = item {
                if let LinkRef::Linked(name) = &trg.address {
                    self.hw_register_names.push(name.clone());
                }
            }
        }
    }

    fn collect_ffi_bindings(&mut self, program: &Program) {
        self.ffi_bindings.clear();
        self.ffi_state = program.ffi.clone();

        for item in &program.items {
            if let TopLevel::ForeignBinding { name, signature, .. } = item {
                self.ffi_bindings.push((name.clone(), signature.clone()));
            }
        }
    }

    fn collect_constants(&mut self, program: &Program) {
        self.constants.clear();
        for item in &program.items {
            if let TopLevel::Constant(c) = item {
                let value = self.expr_to_c(&c.expr);
                self.constants.push((c.name.clone(), value));
            }
        }
    }

    fn is_constant(&self, name: &str) -> bool {
        self.constants.iter().any(|(n, _)| n == name)
    }

    fn get_constant_value(&self, name: &str) -> Option<String> {
        self.constants.iter().find(|(n, _)| n == name).map(|(_, v)| v.clone())
    }

    fn is_local_var(&self, name: &str) -> bool {
        self.local_vars.iter().any(|n| n == name)
    }

    fn add_local_var(&mut self, name: &str) {
        self.local_vars.push(name.to_string());
    }

    fn clear_local_vars(&mut self) {
        self.local_vars.clear();
    }

    fn is_hw_register(&self, name: &str) -> bool {
        self.hw_register_names.iter().any(|n| n == name)
    }

    fn generate_linkage_defines(&self, output: &mut String) {
        let Some(linkage) = &self.linkage else { return; };

        // Generate #define for each linked hardware register
        for name in &self.hw_register_names {
            if let Some(c_addr) = linkage.resolve_c(name) {
                let upper_name = name.to_uppercase();
                output.push_str(&format!("/* @ link: {} -> {} */\n", name, c_addr));
                output.push_str(&format!("#define {}_ADDR {}\n", upper_name, c_addr));
                output.push_str(&format!("#define {} (*(volatile uint32_t *){}_ADDR)\n", upper_name, upper_name));
                output.push_str("\n");
            }
        }
    }

    fn generate_ffi_declarations(&self, output: &mut String) {
        if self.ffi_bindings.is_empty() {
            return;
        }

        output.push_str("/* FFI Function Declarations */\n");

        // Generate #defines for constants
        if !self.constants.is_empty() {
            output.push_str("\n/* Constant Definitions */\n");
            for (name, value) in &self.constants {
                output.push_str(&format!("#define {} {}\n", Self::sanitize_name(name), value));
            }
        }

        for (name, sig) in &self.ffi_bindings {
            // In kernel mode (linux), skip printk - it's provided by kernel headers
            if self.kernel_os == Some("linux".to_string()) && name == "printk" {
                continue;
            }

            // In test mode with stubs, skip extern declarations (stubs are static)
            if self.kernel_mode && self.test_mode {
                continue;
            }

            let return_type = if sig.success_output.is_empty() {
                "void".to_string()
            } else {
                // Use first output field's type
                let (_, ty) = &sig.success_output[0];
                Self::get_c_type(ty)
            };

            let params: Vec<String> = sig.inputs.iter().map(|(param_name, ty)| {
                format!("{} {}", Self::get_c_type(ty), Self::sanitize_name(param_name))
            }).collect();

            let params_str = if params.is_empty() {
                "void".to_string()
            } else {
                params.join(", ")
            };

            output.push_str(&format!("extern {} {}({});\n", return_type, Self::sanitize_name(name), params_str));
        }

        output.push_str("\n");

        // Generate stub implementations for test mode
        if self.kernel_mode && self.test_mode {
            output.push_str("/* FFI Stub Implementations (test mode - safe, no real hardware) */\n");
            for (name, sig) in &self.ffi_bindings {
                self.generate_ffi_stub(name, sig, output);
            }
            output.push_str("\n");
        }
    }

    fn generate_ffi_stub(&self, name: &str, sig: &ForeignSignature, output: &mut String) {
        // In kernel mode (linux), printk is provided by kernel headers - don't stub it
        if self.kernel_os == Some("linux".to_string()) && name == "printk" {
            return;
        }

        let return_type = if sig.success_output.is_empty() {
            "void".to_string()
        } else {
            let (_, ty) = &sig.success_output[0];
            Self::get_c_type(ty)
        };

        let params: Vec<String> = sig.inputs.iter().map(|(param_name, ty)| {
            format!("{} {}", Self::get_c_type(ty), Self::sanitize_name(param_name))
        }).collect();

        let params_str = if params.is_empty() {
            "void".to_string()
        } else {
            params.join(", ")
        };

        output.push_str(&format!("static {} {}({}) {{\n", return_type, name, params_str));
        output.push_str(&format!("    printk(\"[VITRIOL-STUB] {} called\\\\n\");\n", name));

        // Return appropriate stub value based on return type
        match return_type.as_str() {
            "void" => {}
            "uint32_t" => output.push_str("    return 1;  // stub: success handle\n"),
            "int32_t" => output.push_str("    return 1;  // stub: success handle\n"),
            "uint64_t" => output.push_str("    return 1;  // stub: success handle\n"),
            "bool" => output.push_str("    return true;  // stub: success\n"),
            _ => output.push_str("    return 0;\n"),
        }
        output.push_str("}\n\n");
    }

    fn generate_ffi_call(&self, name: &str, args: &[Expr], output: &mut String) {
        // Find the signature for this FFI function
        let sig = self.ffi_bindings.iter()
            .find(|(n, _)| n == name)
            .map(|(_, s)| s);

        let Some(signature) = sig else {
            output.push_str(&format!("    /* FFI function '{}' not found */\n", name));
            return;
        };

        // Check if it's fire-and-forget (frgn!)
        let is_fire_and_forget = matches!(
            signature.ffi_kind,
            Some(crate::ast::FfiKind::FrgnBang)
        );

        // Generate arguments
        let args_str: Vec<String> = args.iter()
            .map(|a| self.expr_to_c(a))
            .collect();
        let args_csv = args_str.join(", ");

        if is_fire_and_forget {
            // Fire-and-forget: just call the function
            output.push_str(&format!("    {}({});\n", Self::sanitize_name(name), args_csv));
        } else {
            // Standard FFI with Result - generate error handling
            let result_var = format!("_result_{}", Self::sanitize_name(name));
            let return_type = if signature.success_output.is_empty() {
                "void".to_string()
            } else {
                let (_, ty) = &signature.success_output[0];
                Self::get_c_type(ty)
            };

            if return_type != "void" {
                // Generate result variable and error check
                output.push_str(&format!("    /* FFI call to {} with error handling */\n", name));
                output.push_str(&format!("    {} {} = {}({});\n", return_type, result_var, Self::sanitize_name(name), args_csv));
                
                // Generate bounds check
                let bounds_check = generate_bounds_check(&self.error_conventions, &result_var, &format!("ffi_error_{}", name));
                output.push_str(&bounds_check);
                
                // Generate error label for this FFI call
                output.push_str(&format!("    goto ffi_ok_{};\n", name));
                output.push_str(&format!("ffi_error_{}:\n", name));
                output.push_str(&format!("    /* FFI error occurred for {} */\n", name));
                output.push_str(&format!("ffi_ok_{}:\n", name));
            } else {
                // Void return - just call
                output.push_str(&format!("    /* FFI call to {} */\n", name));
                output.push_str(&format!("    {}({});\n", Self::sanitize_name(name), args_csv));
            }
        }
    }

    fn generate_ffi_assignment(&self, name: &str, args: &[Expr], target: &str, output: &mut String) {
        // Find the signature for this FFI function
        let sig = self.ffi_bindings.iter()
            .find(|(n, _)| n == name)
            .map(|(_, s)| s);

        let Some(signature) = sig else {
            output.push_str(&format!("    /* FFI function '{}' not found */\n", name));
            return;
        };

        // Generate arguments
        let args_str: Vec<String> = args.iter()
            .map(|a| self.expr_to_c(a))
            .collect();
        let args_csv = args_str.join(", ");

        let return_type = if signature.success_output.is_empty() {
            "void".to_string()
        } else {
            let (_, ty) = &signature.success_output[0];
            Self::get_c_type(ty)
        };

        let result_var = format!("_result_{}", Self::sanitize_name(name));

        if return_type != "void" {
            // Generate FFI call with result stored to target
            output.push_str(&format!("    /* FFI call to {} with error handling */\n", name));
            output.push_str(&format!("    {} {} = {}({});\n", return_type, result_var, Self::sanitize_name(name), args_csv));
            
            // Generate bounds check
            let bounds_check = generate_bounds_check(&self.error_conventions, &result_var, &format!("ffi_error_{}", name));
            output.push_str(&bounds_check);
            
            // Store result to target
            output.push_str(&format!("    state->{} = {};\n", Self::sanitize_name(target), result_var));
            output.push_str(&format!("    goto ffi_ok_{};\n", name));
            output.push_str(&format!("ffi_error_{}:\n", name));
            output.push_str(&format!("    /* FFI error occurred for {} */\n", name));
            // For error case, store default/error value
            output.push_str(&format!("    state->{} = 0;\n", Self::sanitize_name(target)));
            output.push_str(&format!("ffi_ok_{}:\n", name));
        } else {
            // Void return - just call
            output.push_str(&format!("    {}({});\n", Self::sanitize_name(name), args_csv));
        }
    }

    fn collect_state_declarations(&self, program: &Program) -> Vec<(String, Type)> {
        let mut decls = Vec::new();
        for item in &program.items {
            if let TopLevel::StateDecl(decl) = item {
                decls.push((decl.name.clone(), decl.ty.clone()));
            }
        }
        decls
    }

    fn collect_transactions(&self, program: &Program) -> Vec<(String, crate::ast::Transaction)> {
        let mut txns = Vec::new();
        for item in &program.items {
            if let TopLevel::Transaction(txn) = item {
                txns.push((txn.name.clone(), txn.clone()));
            }
        }
        txns
    }

    fn statement_to_c(&mut self, output: &mut String, stmt: &Statement) {
        match stmt {
            Statement::Assignment { lhs, expr, .. } => {
                let name = match lhs {
                    Expr::Identifier(n) | Expr::OwnedRef(n) => n.clone(),
                    _ => return,
                };

                // Check if expr is an FFI call
                if let Expr::Call(func_name, args) = expr {
                    let is_ffi = self.ffi_bindings.iter().any(|(n, _)| n == func_name);
                    if is_ffi {
                        // Generate FFI call with result handling
                        self.generate_ffi_assignment(&func_name, args, &name, output);
                        return;
                    }
                }

                let expr_code = self.expr_to_c(expr);
                // Check if lhs is a hardware register (shouldn't happen for assignments, but handle anyway)
                if self.is_hw_register(&name) {
                    // Direct write to hardware register
                    let upper = name.to_uppercase();
                    output.push_str(&format!("    {} = {};\n", upper, expr_code));
                } else {
                    output.push_str(&format!("    state->{} = {};\n", Self::sanitize_name(&name), expr_code));
                }
            }
            Statement::Let { name, expr, .. } => {
                if let Some(e) = expr {
                    // Check if expr is an FFI call
                    if let Expr::Call(func_name, args) = e {
                        let is_ffi = self.ffi_bindings.iter().any(|(n, _)| n == func_name);
                        if is_ffi {
                            // Generate FFI call with result
                            let sig = self.ffi_bindings.iter()
                                .find(|(n, _)| n == func_name)
                                .map(|(_, s)| s);
                            if let Some(signature) = sig {
                                let return_type = if signature.success_output.is_empty() {
                                    "void".to_string()
                                } else {
                                    let (_, ty) = &signature.success_output[0];
                                    Self::get_c_type(ty)
                                };
                                if return_type != "void" {
                                    let args_str: Vec<String> = args.iter()
                                        .map(|a| self.expr_to_c(a))
                                        .collect();
                                    let args_csv = args_str.join(", ");
                                    output.push_str(&format!("    {} {} = {}({});\n", 
                                        return_type, Self::sanitize_name(name), 
                                        Self::sanitize_name(func_name), args_csv));
                                    self.add_local_var(name);
                                    return;
                                }
                            }
                        }
                    }
                    let expr_code = self.expr_to_c(e);
                    let ty = "int32_t".to_string();
                    output.push_str(&format!("    {} {} = {};\n", ty, Self::sanitize_name(name), expr_code));
                    self.add_local_var(name);
                }
            }
            Statement::Guarded { condition, statements } => {
                // Generate: if (condition) { statements }
                let cond_str = self.expr_to_c(condition);
                output.push_str(&format!("    if ({}) {{\n", cond_str));
                for stmt in statements {
                    self.statement_to_c(output, stmt);
                }
                output.push_str("    }\n");
            }
            Statement::InlineAsm { asm_string, clobbers, .. } => {
                output.push_str(&format!("    /* asm: {} */\n", asm_string));

                if clobbers.is_empty() {
                    output.push_str("    __asm__ __volatile__(\n");
                    output.push_str(&format!("        \"{} \\n\"\n", asm_string));
                    output.push_str("    );\n");
                } else {
                    // Clobbers go in the third section: : : : "reg1", "reg2"
                    let clobber_list = clobbers.iter()
                        .map(|c| format!("\"{}\"", c.as_str()))
                        .collect::<Vec<_>>()
                        .join(", ");
                    output.push_str("    __asm__ __volatile__(\n");
                    output.push_str(&format!("        \"{} \\n\"\n", asm_string));
                    output.push_str(&format!("        : : : {}\n", clobber_list));
                    output.push_str("    );\n");
                }
            }
            Statement::Term(_) => {
                output.push_str("    /* transaction complete */\n");
            }
            Statement::Expression(expr) => {
                // Check if this is an FFI call
                if let Expr::Call(name, args) = expr {
                    // Check if it's an FFI function
                    let is_ffi = self.ffi_bindings.iter().any(|(n, _)| n == name);
                    if is_ffi {
                        self.generate_ffi_call(name, args, output);
                    } else {
                        let expr_code = self.expr_to_c(expr);
                        output.push_str(&format!("    {};\n", expr_code));
                    }
                } else {
                    let expr_code = self.expr_to_c(expr);
                    output.push_str(&format!("    {};\n", expr_code));
                }
            }
            _ => {
                output.push_str("    /* statement not implemented */\n");
            }
        }
    }

    fn expr_to_c(&self, expr: &Expr) -> String {
        match expr {
            Expr::Integer(n) => n.to_string(),
            Expr::Float(f) => f.to_string(),
            Expr::Bool(b) => (if *b { "true" } else { "false" }).to_string(),
            Expr::String(s) => format!("\"{}\"", s),
            Expr::Identifier(n) => {
                // Check if this is a constant first
                if self.is_constant(n) {
                    return self.get_constant_value(n).unwrap_or_else(|| n.clone());
                }
                // Check if this is a local variable
                if self.is_local_var(n) {
                    return Self::sanitize_name(n);
                }
                // Check if this is a hardware register
                if self.is_hw_register(n) {
                    n.to_uppercase()
                } else {
                    format!("state->{}", Self::sanitize_name(n))
                }
            }
            Expr::OwnedRef(n) => {
                if self.is_constant(n) {
                    return self.get_constant_value(n).unwrap_or_else(|| n.clone());
                }
                if self.is_local_var(n) {
                    return Self::sanitize_name(n);
                }
                if self.is_hw_register(n) {
                    n.to_uppercase()
                } else {
                    format!("state->{}", Self::sanitize_name(n))
                }
            }
            Expr::PriorState(n) => {
                if self.is_constant(n) {
                    return self.get_constant_value(n).unwrap_or_else(|| n.clone());
                }
                if self.is_local_var(n) {
                    return Self::sanitize_name(n);
                }
                format!("state->{}", Self::sanitize_name(n))
            }
            Expr::Add(a, b) => format!("({} + {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Sub(a, b) => format!("({} - {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Mul(a, b) => format!("({} * {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Div(a, b) => format!("({} / {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Eq(a, b) => format!("({} == {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Ne(a, b) => format!("({} != {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Lt(a, b) => format!("({} < {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Le(a, b) => format!("({} <= {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Gt(a, b) => format!("({} > {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Ge(a, b) => format!("({} >= {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::And(a, b) => format!("({} && {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Or(a, b) => format!("({} || {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Not(a) => format!("!{}", self.expr_to_c(a)),
            Expr::Neg(a) => format!("-{}", self.expr_to_c(a)),
            _ => "0 /* expr not implemented */".to_string(),
        }
    }

    fn get_c_type(ty: &Type) -> String {
        match ty {
            Type::Int => "int32_t".to_string(),
            Type::UInt => "uint32_t".to_string(),
            Type::Float => "double".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "char *".to_string(),
            _ => "int32_t".to_string(),
        }
    }

    fn get_default_value(ty: &Type) -> String {
        match ty {
            Type::Int => "0".to_string(),
            Type::UInt => "0".to_string(),
            Type::Float => "0.0".to_string(),
            Type::Bool => "false".to_string(),
            Type::String => "NULL".to_string(),
            _ => "0".to_string(),
        }
    }

    fn sanitize_name(name: &str) -> String {
        name.replace('-', "_")
    }
}

impl Default for CBackend {
    fn default() -> Self {
        Self::new()
    }
}