// Copyright 2026 Randy Smits-Schreuder Goedheijt
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::ast::{Expr, Program, Statement, TopLevel, Type};

pub struct CBackend;

impl CBackend {
    pub fn new() -> Self {
        Self
    }

    pub fn generate(&self, program: &Program) -> String {
        let mut output = String::new();

        output.push_str("/* C application - generated by Brief */\n");
        output.push_str("/* Target: Desktop/Embedded Linux, Cortex-M */\n\n");

        output.push_str("#include <stdint.h>\n");
        output.push_str("#include <stdbool.h>\n");
        output.push_str("#include <stdio.h>\n");
        output.push_str("#include <stdlib.h>\n\n");

        let state_decls = self.collect_state_declarations(program);

        output.push_str("typedef struct {\n");
        for (name, ty) in &state_decls {
            let c_type = Self::get_c_type(ty);
            output.push_str(&format!("    {} {};\n", c_type, Self::sanitize_name(name)));
        }
        output.push_str("} State;\n\n");

        output.push_str("static State *state = NULL;\n\n");

        output.push_str("void state_init(void) {\n");
        for (name, ty) in &state_decls {
            let default_val = Self::get_default_value(ty);
            output.push_str(&format!("    state->{} = {};\n", Self::sanitize_name(name), default_val));
        }
        output.push_str("}\n\n");

        for (_, txn) in self.collect_transactions(program) {
            output.push_str(&format!(
                "bool {}(void) {{\n",
                Self::sanitize_name(&txn.name)
            ));
            output.push_str(&format!(
                "    /* pre: {:?} */\n",
                txn.contract.pre_condition
            ));

            for stmt in &txn.body {
                self.statement_to_c(&mut output, stmt);
            }

            output.push_str(&format!(
                "    /* post: {:?} */\n",
                txn.contract.post_condition
            ));
            output.push_str("    return true;\n");
            output.push_str("}\n\n");
        }

        output.push_str("int main(void) {\n");
        output.push_str("    state = (State *)malloc(sizeof(State));\n");
        output.push_str("    state_init();\n");
        output.push_str("    printf(\"Brief kernel starting\\n\");\n");

        if let Some((name, _)) = self.collect_transactions(program).first() {
            output.push_str(&format!("    {}();\n", Self::sanitize_name(name)));
        }

        output.push_str("    printf(\"Brief kernel done\\n\");\n");
        output.push_str("    free(state);\n");
        output.push_str("    return 0;\n");
        output.push_str("}\n");

        output
    }

    fn collect_state_declarations(&self, program: &Program) -> Vec<(String, Type)> {
        let mut decls = Vec::new();
        for item in &program.items {
            if let TopLevel::StateDecl(decl) = item {
                decls.push((decl.name.clone(), decl.ty.clone()));
            }
        }
        decls
    }

    fn collect_transactions(&self, program: &Program) -> Vec<(String, crate::ast::Transaction)> {
        let mut txns = Vec::new();
        for item in &program.items {
            if let TopLevel::Transaction(txn) = item {
                txns.push((txn.name.clone(), txn.clone()));
            }
        }
        txns
    }

    fn statement_to_c(&self, output: &mut String, stmt: &Statement) {
        match stmt {
            Statement::Assignment { lhs, expr, .. } => {
                let name = match lhs {
                    Expr::Identifier(n) | Expr::OwnedRef(n) => n.clone(),
                    _ => return,
                };
                let expr_code = self.expr_to_c(expr);
                output.push_str(&format!("    state->{} = {};\n", Self::sanitize_name(&name), expr_code));
            }
            Statement::Let { name, expr, .. } => {
                if let Some(e) = expr {
                    let expr_code = self.expr_to_c(e);
                    let ty = "int32_t".to_string();
                    output.push_str(&format!("    {} {} = {};\n", ty, Self::sanitize_name(name), expr_code));
                }
            }
            Statement::InlineAsm { asm_string, clobbers, .. } => {
                let clobber_list = if clobbers.is_empty() {
                    String::new()
                } else {
                    clobbers.iter()
                        .map(|c| c.as_str())
                        .collect::<Vec<_>>()
                        .join(", ")
                };

                output.push_str(&format!("    /* asm: {} */\n", asm_string));

                if clobbers.is_empty() {
                    output.push_str("    __asm__ __volatile__(\n");
                    output.push_str(&format!("        \"{} \\n\"\n", asm_string));
                    output.push_str("    );\n");
                } else {
                    output.push_str("    __asm__ __volatile__(\n");
                    output.push_str(&format!("        \"{} \\n\"\n", asm_string));
                    output.push_str(&format!(
                        "        : : \"r\" (state->{}), \"r\" ({})\n",
                        Self::sanitize_name(&clobbers[0]),
                        clobber_list
                    ));
                    output.push_str("    );\n");
                }
            }
            Statement::Term(_) => {
                output.push_str("    /* transaction complete */\n");
            }
            Statement::Expression(expr) => {
                let expr_code = self.expr_to_c(expr);
                output.push_str(&format!("    {};\n", expr_code));
            }
            _ => {
                output.push_str("    /* statement not implemented */\n");
            }
        }
    }

    fn expr_to_c(&self, expr: &Expr) -> String {
        match expr {
            Expr::Integer(n) => n.to_string(),
            Expr::Float(f) => f.to_string(),
            Expr::Bool(b) => (if *b { "true" } else { "false" }).to_string(),
            Expr::String(s) => format!("\"{}\"", s),
            Expr::Identifier(n) => format!("state->{}", Self::sanitize_name(n)),
            Expr::OwnedRef(n) => format!("state->{}", Self::sanitize_name(n)),
            Expr::PriorState(n) => format!("state->{}", Self::sanitize_name(n)),
            Expr::Add(a, b) => format!("({} + {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Sub(a, b) => format!("({} - {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Mul(a, b) => format!("({} * {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Div(a, b) => format!("({} / {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Eq(a, b) => format!("({} == {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Ne(a, b) => format!("({} != {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Lt(a, b) => format!("({} < {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Le(a, b) => format!("({} <= {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Gt(a, b) => format!("({} > {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Ge(a, b) => format!("({} >= {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::And(a, b) => format!("({} && {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Or(a, b) => format!("({} || {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Not(a) => format!("!{}", self.expr_to_c(a)),
            Expr::Neg(a) => format!("-{}", self.expr_to_c(a)),
            _ => "0 /* expr not implemented */".to_string(),
        }
    }

    fn get_c_type(ty: &Type) -> String {
        match ty {
            Type::Int => "int32_t".to_string(),
            Type::UInt => "uint32_t".to_string(),
            Type::Float => "double".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "char *".to_string(),
            _ => "int32_t".to_string(),
        }
    }

    fn get_default_value(ty: &Type) -> String {
        match ty {
            Type::Int => "0".to_string(),
            Type::UInt => "0".to_string(),
            Type::Float => "0.0".to_string(),
            Type::Bool => "false".to_string(),
            Type::String => "NULL".to_string(),
            _ => "0".to_string(),
        }
    }

    fn sanitize_name(name: &str) -> String {
        name.replace('-', "_")
    }
}

impl Default for CBackend {
    fn default() -> Self {
        Self::new()
    }
}