// Copyright 2026 Randy Smits-Schreuder Goedheijt
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::ast::{Expr, LinkRef, Program, Statement, TopLevel, Type};
use crate::linkage::LinkageConfig;

pub struct CBackend {
    linkage: Option<LinkageConfig>,
    hw_register_names: Vec<String>,
    bare_metal: bool,
    kernel_mode: bool,              // NEW: kernel module target
    kernel_os: Option<String>,     // NEW: "linux", "windows", etc.
}

impl CBackend {
    pub fn new() -> Self {
        Self {
            linkage: None,
            hw_register_names: Vec::new(),
            bare_metal: false,
            kernel_mode: false,
            kernel_os: None,
        }
    }

    pub fn with_linkage(mut self, linkage: LinkageConfig) -> Self {
        self.linkage = Some(linkage);
        self
    }

    pub fn bare_metal(mut self, bare_metal: bool) -> Self {
        self.bare_metal = bare_metal;
        self
    }

    pub fn with_kernel_mode(mut self, os: Option<String>) -> Self {
        self.kernel_mode = true;
        self.kernel_os = os;
        self
    }

    pub fn generate(&mut self, program: &Program) -> (String, Option<String>) {
        // Collect hardware register names first
        self.collect_hw_registers(program);

        let mut output = String::new();
        let mut makefile = String::new();

        output.push_str("/* C application - generated by Brief */\n");
        if self.kernel_mode {
            output.push_str("/* Target: Kernel Module */\n\n");
        } else if self.bare_metal {
            output.push_str("/* Target: Bare-metal ARM (Cortex-A) */\n\n");
        } else {
            output.push_str("/* Target: Hosted (Desktop/Embedded Linux) */\n\n");
        }

        // Include headers based on mode
        if self.kernel_mode {
            // Kernel mode: include kernel headers
            if let Some(os) = &self.kernel_os {
                match os.as_str() {
                    "linux" => {
                        output.push_str("#include <linux/module.h>\n");
                        output.push_str("#include <linux/kernel.h>\n");
                        output.push_str("#include <linux/kthread.h>\n");
                        output.push_str("#include <linux/delay.h>\n");
                    }
                    _ => {}
                }
            } else {
                // Default kernel headers
                output.push_str("#include <linux/module.h>\n");
                output.push_str("#include <linux/kernel.h>\n");
                output.push_str("#include <linux/kthread.h>\n");
                output.push_str("#include <linux/delay.h>\n");
            }
        } else {
            output.push_str("#include <stdint.h>\n");
            output.push_str("#include <stdbool.h>\n");
            output.push_str("#include <stddef.h>\n");
        }
        if !self.bare_metal && !self.kernel_mode {
            output.push_str("#include <stdlib.h>\n");
        }
        output.push_str("\n");

        // Generate MMIO definitions from @ link references
        self.generate_linkage_defines(&mut output);

        let state_decls = self.collect_state_declarations(program);

        // Only generate struct for non-hardware state
        if !state_decls.is_empty() {
            output.push_str("typedef struct {\n");
            for (name, ty) in &state_decls {
                let c_type = Self::get_c_type(ty);
                output.push_str(&format!("    {} {};\n", c_type, Self::sanitize_name(name)));
            }
            output.push_str("} State;\n\n");

            if self.bare_metal {
                // Static allocation for bare-metal (no malloc)
                output.push_str("static State state_instance;\n");
                output.push_str("static State *state = &state_instance;\n\n");
            } else {
                // Dynamic allocation for hosted (desktop/embedded Linux)
                output.push_str("static State *state = NULL;\n\n");
            }

            output.push_str("void state_init(void) {\n");
            for (name, ty) in &state_decls {
                let default_val = Self::get_default_value(ty);
                output.push_str(&format!("    state->{} = {};\n", Self::sanitize_name(name), default_val));
            }
            output.push_str("}\n\n");
        }

        for (_, txn) in self.collect_transactions(program) {
            output.push_str(&format!(
                "bool {}(void) {{\n",
                Self::sanitize_name(&txn.name)
            ));
            output.push_str(&format!(
                "    /* pre: {:?} */\n",
                txn.contract.pre_condition
            ));

            for stmt in &txn.body {
                self.statement_to_c(&mut output, stmt);
            }

            output.push_str(&format!(
                "    /* post: {:?} */\n",
                txn.contract.post_condition
            ));
            output.push_str("    return true;\n");
            output.push_str("}\n\n");
        }

        output.push_str("void brief_init(void) {\n");
        let state_decls = self.collect_state_declarations(program);
        if !state_decls.is_empty() {
            if self.bare_metal || self.kernel_mode {
                output.push_str("    // Static allocation for bare-metal/kernel\n");
                output.push_str("    state_init();\n");
            } else {
                output.push_str("    state = (State *)malloc(sizeof(State));\n");
                output.push_str("    state_init();\n");
            }
        }
        output.push_str("}\n\n");

        // Generate appropriate entry point based on mode
        if self.kernel_mode {
            // Kernel module: generate module_init/module_exit
            output.push_str("\n// Kernel module entry points\n");
            
            // Find first transaction that fires (entry point)
            let entry_txn = self.find_entry_point(program);
            
            // Generate module_init
            output.push_str("static int __init brief_init(void) {\n");
            if let Some(entry_name) = entry_txn {
                output.push_str(&format!("    {}();\n", Self::sanitize_name(&entry_name)));
            }
            output.push_str("    return 0;\n");
            output.push_str("}\n");
            output.push_str("module_init(brief_init);\n\n");
            
            // Generate module_exit (look for "exit" transaction)
            let exit_txn = self.find_exit_point(program);
            output.push_str("static void __exit brief_exit(void) {\n");
            if let Some(exit_name) = exit_txn {
                output.push_str(&format!("    {}();\n", Self::sanitize_name(&exit_name)));
            }
            output.push_str("}\n");
            output.push_str("module_exit(brief_exit);\n\n");
            
            // MODULE_LICENSE
            output.push_str("MODULE_LICENSE(\"GPL\");\n");
        } else {
            // Normal/embedded: generate main()
            output.push_str("int main(void) {\n");
            let state_decls = self.collect_state_declarations(program);
            if !state_decls.is_empty() {
                output.push_str("    brief_init();\n");
            }
            output.push_str("    return 0;\n");
            output.push_str("}\n");
        }

        // Generate Makefile for kernel modules
        let makefile = if self.kernel_mode {
            Some(self.generate_makefile())
        } else {
            None
        };

        (output, makefile)
    }

    fn find_entry_point(&self, program: &Program) -> Option<String> {
        // Find first transaction that can fire (precondition is true in initial state)
        // This is a simplified version - full logic is in analysis/entry_point.rs
        for item in &program.items {
            if let TopLevel::Transaction(txn) = item {
                // Check if precondition is true (simplified check)
                if let Expr::Bool(true) = txn.contract.pre_condition {
                    return Some(txn.name.clone());
                }
            }
        }
        None
    }

    fn find_exit_point(&self, program: &Program) -> Option<String> {
        // Look for transaction named "exit" or last non-rct transaction
        let mut last_txn = None;
        for item in &program.items {
            if let TopLevel::Transaction(txn) = item {
                if txn.name == "exit" {
                    return Some(txn.name.clone());
                }
                if !txn.is_reactive && !txn.is_async {
                    last_txn = Some(txn.name.clone());
                }
            }
        }
        last_txn
    }

    fn generate_makefile(&self) -> String {
        let mut makefile = String::new();
        makefile.push_str("# Auto-generated Makefile for kernel module\n");
        makefile.push_str("obj-m += brief_module.o\n");
        makefile.push_str("brief_module-objs := generated.o\n\n");
        makefile.push_str("all:\n");
        makefile.push_str("\tmake -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules\n\n");
        makefile.push_str("clean:\n");
        makefile.push_str("\tmake -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean\n");
        makefile
    }

    fn collect_hw_registers(&mut self, program: &Program) {
        self.hw_register_names.clear();
        for item in &program.items {
            if let TopLevel::Trigger(trg) = item {
                if let LinkRef::Linked(name) = &trg.address {
                    self.hw_register_names.push(name.clone());
                }
            }
        }
    }

    fn is_hw_register(&self, name: &str) -> bool {
        self.hw_register_names.iter().any(|n| n == name)
    }

    fn generate_linkage_defines(&self, output: &mut String) {
        let Some(linkage) = &self.linkage else { return; };

        // Generate #define for each linked hardware register
        for name in &self.hw_register_names {
            if let Some(c_addr) = linkage.resolve_c(name) {
                let upper_name = name.to_uppercase();
                output.push_str(&format!("/* @ link: {} -> {} */\n", name, c_addr));
                output.push_str(&format!("#define {}_ADDR {}\n", upper_name, c_addr));
                output.push_str(&format!("#define {} (*(volatile uint32_t *){}_ADDR)\n", upper_name, upper_name));
                output.push_str("\n");
            }
        }
    }

    fn collect_state_declarations(&self, program: &Program) -> Vec<(String, Type)> {
        let mut decls = Vec::new();
        for item in &program.items {
            if let TopLevel::StateDecl(decl) = item {
                decls.push((decl.name.clone(), decl.ty.clone()));
            }
        }
        decls
    }

    fn collect_transactions(&self, program: &Program) -> Vec<(String, crate::ast::Transaction)> {
        let mut txns = Vec::new();
        for item in &program.items {
            if let TopLevel::Transaction(txn) = item {
                txns.push((txn.name.clone(), txn.clone()));
            }
        }
        txns
    }

    fn statement_to_c(&self, output: &mut String, stmt: &Statement) {
        match stmt {
            Statement::Assignment { lhs, expr, .. } => {
                let name = match lhs {
                    Expr::Identifier(n) | Expr::OwnedRef(n) => n.clone(),
                    _ => return,
                };
                let expr_code = self.expr_to_c(expr);
                // Check if lhs is a hardware register (shouldn't happen for assignments, but handle anyway)
                if self.is_hw_register(&name) {
                    // Direct write to hardware register
                    let upper = name.to_uppercase();
                    output.push_str(&format!("    {} = {};\n", upper, expr_code));
                } else {
                    output.push_str(&format!("    state->{} = {};\n", Self::sanitize_name(&name), expr_code));
                }
            }
            Statement::Let { name, expr, .. } => {
                if let Some(e) = expr {
                    let expr_code = self.expr_to_c(e);
                    let ty = "int32_t".to_string();
                    output.push_str(&format!("    {} {} = {};\n", ty, Self::sanitize_name(name), expr_code));
                }
            }
            Statement::InlineAsm { asm_string, clobbers, .. } => {
                output.push_str(&format!("    /* asm: {} */\n", asm_string));

                if clobbers.is_empty() {
                    output.push_str("    __asm__ __volatile__(\n");
                    output.push_str(&format!("        \"{} \\n\"\n", asm_string));
                    output.push_str("    );\n");
                } else {
                    // Clobbers go in the third section: : : : "reg1", "reg2"
                    let clobber_list = clobbers.iter()
                        .map(|c| format!("\"{}\"", c.as_str()))
                        .collect::<Vec<_>>()
                        .join(", ");
                    output.push_str("    __asm__ __volatile__(\n");
                    output.push_str(&format!("        \"{} \\n\"\n", asm_string));
                    output.push_str(&format!("        : : : {}\n", clobber_list));
                    output.push_str("    );\n");
                }
            }
            Statement::Term(_) => {
                output.push_str("    /* transaction complete */\n");
            }
            Statement::Expression(expr) => {
                let expr_code = self.expr_to_c(expr);
                output.push_str(&format!("    {};\n", expr_code));
            }
            _ => {
                output.push_str("    /* statement not implemented */\n");
            }
        }
    }

    fn expr_to_c(&self, expr: &Expr) -> String {
        match expr {
            Expr::Integer(n) => n.to_string(),
            Expr::Float(f) => f.to_string(),
            Expr::Bool(b) => (if *b { "true" } else { "false" }).to_string(),
            Expr::String(s) => format!("\"{}\"", s),
            Expr::Identifier(n) => {
                // Check if this is a hardware register
                if self.is_hw_register(n) {
                    n.to_uppercase()
                } else {
                    format!("state->{}", Self::sanitize_name(n))
                }
            }
            Expr::OwnedRef(n) => {
                if self.is_hw_register(n) {
                    n.to_uppercase()
                } else {
                    format!("state->{}", Self::sanitize_name(n))
                }
            }
            Expr::PriorState(n) => format!("state->{}", Self::sanitize_name(n)),
            Expr::Add(a, b) => format!("({} + {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Sub(a, b) => format!("({} - {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Mul(a, b) => format!("({} * {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Div(a, b) => format!("({} / {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Eq(a, b) => format!("({} == {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Ne(a, b) => format!("({} != {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Lt(a, b) => format!("({} < {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Le(a, b) => format!("({} <= {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Gt(a, b) => format!("({} > {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Ge(a, b) => format!("({} >= {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::And(a, b) => format!("({} && {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Or(a, b) => format!("({} || {})", self.expr_to_c(a), self.expr_to_c(b)),
            Expr::Not(a) => format!("!{}", self.expr_to_c(a)),
            Expr::Neg(a) => format!("-{}", self.expr_to_c(a)),
            _ => "0 /* expr not implemented */".to_string(),
        }
    }

    fn get_c_type(ty: &Type) -> String {
        match ty {
            Type::Int => "int32_t".to_string(),
            Type::UInt => "uint32_t".to_string(),
            Type::Float => "double".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "char *".to_string(),
            _ => "int32_t".to_string(),
        }
    }

    fn get_default_value(ty: &Type) -> String {
        match ty {
            Type::Int => "0".to_string(),
            Type::UInt => "0".to_string(),
            Type::Float => "0.0".to_string(),
            Type::Bool => "false".to_string(),
            Type::String => "NULL".to_string(),
            _ => "0".to_string(),
        }
    }

    fn sanitize_name(name: &str) -> String {
        name.replace('-', "_")
    }
}

impl Default for CBackend {
    fn default() -> Self {
        Self::new()
    }
}