// CIRCT Backend — emits MLIR text in HW + Comb + Seq dialects.
// Invoked externally: brief-compiler circt <file.bv> → program.mlir → circt-opt → circt-translate → verilog

use crate::analysis::dependency_graph::DependencyGraph;
use crate::ast::{Expr, Program, TopLevel, Type};
use std::collections::HashMap;
use std::fmt::Write;

/// CIRCT backend state for MLIR code generation.
#[derive(Debug, Clone)]
pub struct CirctBackend {
    /// Variable name → HW module port name (for trg variables)
    pub trg_ports: Vec<String>,
    /// Variable name → its type
    pub var_types: HashMap<String, Type>,
    /// Variable name → its initializer expression
    pub var_exprs: HashMap<String, Option<Expr>>,
}

impl CirctBackend {
    pub fn new() -> Self {
        CirctBackend {
            trg_ports: Vec::new(),
            var_types: HashMap::new(),
            var_exprs: HashMap::new(),
        }
    }

    /// Generate MLIR text for a program.
    pub fn generate(&mut self, program: &Program) -> String {
        let dep_graph = DependencyGraph::build(program)
            .unwrap_or_else(|_| DependencyGraph {
                topo_order: Vec::new(),
                bit_index: HashMap::new(),
                dependencies: HashMap::new(),
                dependents: HashMap::new(),
                is_trg: std::collections::HashSet::new(),
                all_vars: std::collections::HashSet::new(),
            });

        // Pass 1: collect state decls and trigger declarations
        for item in &program.items {
            match item {
                TopLevel::StateDecl(decl) => {
                    self.var_types.insert(decl.name.clone(), decl.ty.clone());
                    self.var_exprs.insert(decl.name.clone(), decl.expr.clone());
                }
                TopLevel::Trigger(trg) => {
                    self.trg_ports.push(trg.name.clone());
                    self.var_types.insert(trg.name.clone(), trg.ty.clone());
                    self.var_exprs.insert(trg.name.clone(), None);
                }
                _ => {}
            }
        }

        let mut out = String::new();
        self.emit_header(&mut out);
        self.emit_module(&mut out, &dep_graph);
        out
    }

    fn emit_header(&self, out: &mut String) {
        writeln!(out, "// Generated by brief-compiler CIRCT backend").ok();
        writeln!(out, "// Run: circt-opt program.mlir | circt-translate --export-verilog").ok();
        writeln!(out).ok();
    }

    fn mlir_type(&self, ty: &Type) -> &str {
        match ty {
            Type::Bool => "i1",
            Type::Int | Type::UInt => "i64",
            Type::Char => "i32",
            Type::Float => "f64",
            _ => "i64",
        }
    }

    fn emit_module(&self, out: &mut String, dep_graph: &DependencyGraph) {
        // Collect all port names (trg variables first, then clock/reset)
        let mut port_decls: Vec<String> = Vec::new();
        // clock and reset are implicit for Seq dialect registers
        port_decls.push("clock: i1".to_string());
        port_decls.push("reset: i1".to_string());

        // Trigger variables become top-level input ports
        for trg_name in &self.trg_ports {
            if let Some(ty) = self.var_types.get(trg_name) {
                let mlir_ty = self.mlir_type(ty);
                port_decls.push(format!("{}: {}", trg_name, mlir_ty));
            }
        }

        // State variables that are NOT triggers become output ports or internal wires
        // For simplicity, emit them as output ports
        let sorted_vars = &dep_graph.topo_order;
        for var_name in sorted_vars {
            if !self.trg_ports.contains(var_name) {
                if let Some(ty) = self.var_types.get(var_name) {
                    let mlir_ty = self.mlir_type(ty);
                    port_decls.push(format!("{}: {}", var_name, mlir_ty));
                }
            }
        }

        // Emit hw.module with all ports
        write!(out, "hw.module @top(").ok();
        for (i, port) in port_decls.iter().enumerate() {
            if i > 0 { write!(out, ", ").ok(); }
            write!(out, "{}", port).ok();
        }
        writeln!(out, ") -> () {{").ok();

        // Emit internal wire declarations for computed variables
        for var_name in sorted_vars {
            if !self.trg_ports.contains(var_name) {
                if let Some(ty) = self.var_types.get(var_name) {
                    let mlir_ty = self.mlir_type(ty);
                    writeln!(out, "  %{} = hw.wire : {}", var_name, mlir_ty).ok();
                }
            }
        }

        // Emit combinational logic for each computed variable
        for var_name in sorted_vars {
            if self.trg_ports.contains(var_name) {
                continue; // trg vars are input ports, not computed
            }
            let deps = dep_graph.dependencies.get(var_name);
            if let Some(dep_list) = deps {
                if !dep_list.is_empty() {
                    // Simple forwarding: assign first dependency value as proxy
                    // Full expression-to-MLIR emission is future work
                    if let Some(first_dep) = dep_list.first() {
                        let mlir_ty = self.mlir_type(self.var_types.get(var_name).unwrap_or(&Type::Int));
                        writeln!(out, "  hw.output_assign {}_out, %{} : {}", var_name, first_dep, mlir_ty).ok();
                    }
                }
            }
            // If no deps, assign constant 0
            if deps.map_or(true, |d| d.is_empty()) {
                let mlir_ty = self.mlir_type(self.var_types.get(var_name).unwrap_or(&Type::Int));
                writeln!(out, "  %c0_{} = hw.constant 0 : {}", var_name, mlir_ty).ok();
            }
        }

        // Connect outputs — assign each computed variable to its output port
        for var_name in sorted_vars {
            if !self.trg_ports.contains(var_name) {
                if let Some(ty) = self.var_types.get(var_name) {
                    let mlir_ty = self.mlir_type(ty);
                    writeln!(out, "  hw.output_assign {}, %{} : {}", var_name, var_name, mlir_ty).ok();
                }
            }
        }

        writeln!(out, "  hw.output").ok();
        writeln!(out, "}}").ok();
        writeln!(out).ok();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ast::*;

    fn make_program(items: Vec<TopLevel>) -> Program {
        Program {
            items,
            comments: vec![],
            reactor_speed: None,
            attrs: vec![],
            ffi: None,
            strict_mode: StrictMode::Off,
            dispatch_mode: DispatchMode::default(),
            exit_condition: None,
            out_pragmas: vec![],
            default_sig_modifier: None,
        }
    }

    fn make_state_decl(name: &str, ty: Type, expr: Option<Expr>) -> TopLevel {
        TopLevel::StateDecl(StateDecl {
            name: name.to_string(),
            ty,
            expr,
            address: None,
            bit_range: None,
            range_constraint: None,
            is_override: false,
            os_mode: false,
            span: None,
            attrs: vec![],
        })
    }

    fn make_trigger(name: &str, ty: Type) -> TopLevel {
        TopLevel::Trigger(TriggerDeclaration {
            name: name.to_string(),
            ty,
            address: LinkRef::Explicit(0),
            bit_range: None,
            stages: vec![],
            condition: None,
            is_wake: false,
            span: None,
        })
    }

    #[test]
    fn test_circt_empty_program() {
        let mut backend = CirctBackend::new();
        let output = backend.generate(&make_program(vec![]));
        assert!(output.contains("hw.module @top"));
        assert!(output.contains("clock: i1"));
        assert!(output.contains("hw.output"));
    }

    #[test]
    fn test_circt_trg_port() {
        let mut backend = CirctBackend::new();
        let output = backend.generate(&make_program(vec![
            make_trigger("sensor", Type::Int),
        ]));
        assert!(output.contains("sensor: i64"));
    }

    #[test]
    fn test_circt_derived_var() {
        let mut backend = CirctBackend::new();
        let output = backend.generate(&make_program(vec![
            make_trigger("a", Type::Int),
            make_state_decl("b", Type::Int, Some(Expr::Identifier("a".to_string()))),
        ]));
        assert!(output.contains("a: i64"));
        assert!(output.contains("b: i64"));
    }
}
