// Copyright 2026 Randy Smits-Schreuder Goedheijt
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::ast::{BitRange, Expr, Program, Statement, TopLevel, Type};
use crate::backend::{MemoryOverlay, GuardTracker};
use std::cell::RefCell;
use std::collections::{HashMap, HashSet};

/// Intent: Backend that compiles Brief programs to native Rust source code.
pub struct RustBackend {
    spec: Option<crate::target_spec::TargetSpec>,
    signal_counter: usize,
    txn_counter: usize,
    signal_map: HashMap<String, usize>,
    pending_cleanup: RefCell<Vec<Statement>>,
    has_cycles: bool,
    guard_tracker: GuardTracker,
    enable_guard_cache: bool,
}

impl RustBackend {
    /// Intent: Create a new Rust backend with default configuration.
    pub fn new() -> Self {
        Self {
            spec: None,
            signal_counter: 0,
            txn_counter: 0,
            signal_map: HashMap::new(),
            pending_cleanup: RefCell::new(Vec::new()),
            has_cycles: false,
            guard_tracker: GuardTracker::new(),
            enable_guard_cache: true,
        }
    }

    /// Intent: Attach a target specification for Rust code generation.
    pub fn with_spec(mut self, spec: crate::target_spec::TargetSpec) -> Self {
        self.spec = Some(spec);
        self
    }

    /// Intent: Generate Rust source code from a Brief program.
    pub fn generate(&mut self, program: &Program) -> String {
        // Run shared program analysis
        let _analysis = crate::backend::analyze_program(program, false);
        let cg = &_analysis.call_graph;
        let _pr = &_analysis.param_ranges;
        self.has_cycles = cg.has_cycle();
        if !self.has_cycles {
            println!("  Rust backend: acyclic call graph — static dispatch enabled");
        }

        self.collect_signals(program);

        let mut output = String::new();

        // Build guard tracker
        let state_decls = self.collect_state_declarations(program);
        self.guard_tracker.state_vars = state_decls.iter().map(|(n, _)| n.clone()).collect();
        for (_, txn) in self.collect_transactions(program) {
            let mut deps = Vec::new();
            let mut ids = HashSet::new();
            Self::collect_expr_ids(&txn.contract.pre_condition, &mut ids);
            for id in &ids {
                if self.guard_tracker.state_vars.contains(id) {
                    deps.push(id.clone());
                }
            }
            self.guard_tracker.register_guard(&txn.name, deps);
        }

        output.push_str("// Native Rust application - generated by Brief\n");
        let target_label = self.spec.as_ref()
            .and_then(|s| s.codegen.as_ref())
            .map(|s| s.entry_point.style.as_str())
            .unwrap_or("Desktop/Embedded Linux (std)");
        output.push_str(&format!("// Target: {}\n\n", target_label));

        if let Some(spec) = &self.spec {
            if let Some(cg) = &spec.codegen {
                if let Some(header) = &cg.templates.header {
                    output.push_str(header);
                    output.push_str("\n\n");
                }
            }
        } else {
            output.push_str("use std::fmt;\n\n");
        }

        let memory_overlay = MemoryOverlay::analyze(program);

        output.push_str("#[derive(Debug, Clone)]\n");
        output.push_str("pub struct State {\n");
        if memory_overlay.has_overlays() {
            output.push_str("    // Memory overlay groups (mutually exclusive variables):\n");
            for group in &memory_overlay.groups {
                output.push_str(&format!(
                    "    //   overlaid: {}\n",
                    group.join(", ")
                ));
            }
        }
        for (name, ty) in &state_decls {
            let rust_type = Self::get_rust_type(ty);
            output.push_str(&format!("    pub {}: {},\n", name, rust_type));
        }
        if self.enable_guard_cache {
            for (guard_name, _) in &self.guard_tracker.guard_to_vars {
                output.push_str(&format!("    pub {}_dirty: bool,\n", Self::sanitize_name(guard_name)));
            }
        }
        output.push_str("}\n\n");

        output.push_str("impl Default for State {\n");
        output.push_str("    fn default() -> Self {\n");
        output.push_str("        Self {\n");
        for (name, ty) in &state_decls {
            let default_val = Self::get_default_value(ty);
            output.push_str(&format!("            {}: {},\n", name, default_val));
        }
        if self.enable_guard_cache {
            for (guard_name, _) in &self.guard_tracker.guard_to_vars {
                output.push_str(&format!("            {}_dirty: true,\n", Self::sanitize_name(guard_name)));
            }
        }
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");

        for item in &program.items {
            if let TopLevel::Struct(struct_def) = item {
                output.push_str("#[derive(Debug, Clone)]\n");
                if !struct_def.type_params.is_empty() {
                    let params = struct_def.type_params.join(", ");
                    output.push_str(&format!("pub struct {}<{}> {{\n", struct_def.name, params));
                } else {
                    output.push_str(&format!("pub struct {} {{\n", struct_def.name));
                }
                for field in &struct_def.fields {
                    let rust_type = Self::get_rust_type(&field.ty);
                    output.push_str(&format!("    pub {}: {},\n", field.name, rust_type));
                }
                output.push_str("}\n\n");
            }
        }

        for item in &program.items {
            if let TopLevel::Enum(enum_def) = item {
                output.push_str("#[derive(Debug, Clone)]\n");
                output.push_str(&format!("pub enum {} {{\n", enum_def.name));
                for variant in &enum_def.variants {
                    match variant {
                        crate::ast::EnumVariant::Unit(name) => {
                            output.push_str(&format!("    {},\n", name));
                        }
                        crate::ast::EnumVariant::Tuple(name, types) => {
                            let type_strs: Vec<String> = types.iter().map(|t| Self::get_rust_type(t)).collect();
                            output.push_str(&format!("    {}({}),\n", name, type_strs.join(", ")));
                        }
                        crate::ast::EnumVariant::Struct(name, fields) => {
                            let field_strs: Vec<String> = fields.iter()
                                .map(|(f, t)| format!("{}: {}", f, Self::get_rust_type(t)))
                                .collect();
                            output.push_str(&format!("    {} {{ {} }},\n", name, field_strs.join(", ")));
                        }
                    }
                }
                output.push_str("}\n\n");
            }
        }

        for item in &program.items {
            if let TopLevel::Constant(const_def) = item {
                let rust_type = Self::get_rust_type(&const_def.ty);
                let expr_code = self.expr_to_rust_no_self(&const_def.expr);
                output.push_str(&format!("pub const {}: {} = {};\n\n", const_def.name, rust_type, expr_code));
            }
        }

        for item in &program.items {
            if let TopLevel::Struct(struct_def) = item {
                output.push_str("#[derive(Debug, Clone)]\n");
                if !struct_def.type_params.is_empty() {
                    let params = struct_def.type_params.join(", ");
                    output.push_str(&format!("pub struct {}<{}> {{\n", struct_def.name, params));
                } else {
                    output.push_str(&format!("pub struct {} {{\n", struct_def.name));
                }
                for field in &struct_def.fields {
                    let rust_type = Self::get_rust_type(&field.ty);
                    output.push_str(&format!("    pub {}: {},\n", field.name, rust_type));
                }
                output.push_str("}\n\n");
            }
        }

        for item in &program.items {
            if let TopLevel::Enum(enum_def) = item {
                output.push_str("#[derive(Debug, Clone)]\n");
                output.push_str(&format!("pub enum {} {{\n", enum_def.name));
                for variant in &enum_def.variants {
                    match variant {
                        crate::ast::EnumVariant::Unit(name) => {
                            output.push_str(&format!("    {},\n", name));
                        }
                        crate::ast::EnumVariant::Tuple(name, types) => {
                            let type_strs: Vec<String> = types.iter().map(|t| Self::get_rust_type(t)).collect();
                            output.push_str(&format!("    {}({}),\n", name, type_strs.join(", ")));
                        }
                        crate::ast::EnumVariant::Struct(name, fields) => {
                            let field_strs: Vec<String> = fields.iter()
                                .map(|(f, t)| format!("{}: {}", f, Self::get_rust_type(t)))
                                .collect();
                            output.push_str(&format!("    {} {{ {} }},\n", name, field_strs.join(", ")));
                        }
                    }
                }
                output.push_str("}\n\n");
            }
        }

        for item in &program.items {
            if let TopLevel::Constant(const_def) = item {
                let rust_type = Self::get_rust_type(&const_def.ty);
                let expr_code = self.expr_to_rust_no_self(&const_def.expr);
                output.push_str(&format!("pub const {}: {} = {};\n\n", const_def.name, rust_type, expr_code));
            }
        }

        output.push_str("impl State {\n");

        for (txn_name, txn) in self.collect_transactions(program) {
            let params: Vec<String> = txn.parameters.iter()
                .map(|(n, t)| format!("{}: {}", n, Self::get_rust_type(t)))
                .collect();
            let param_str = if params.is_empty() {
                "&mut self".to_string()
            } else {
                format!("&mut self, {}", params.join(", "))
            };

            let return_type = "bool";
            let sanitized = Self::sanitize_name(&txn_name);
            output.push_str(&format!(
                "    pub fn {}({}) -> {} {{\n",
                sanitized, param_str, return_type
            ));

            // Guard pre-computation: check dirty flag
            if self.enable_guard_cache && self.guard_tracker.guard_to_vars.contains_key(&txn_name) {
                output.push_str(&format!(
                    "        if !self.{}_dirty {{\n            return true;\n        }}\n",
                    sanitized
                ));
                output.push_str(&format!(
                    "        self.{}_dirty = false;\n",
                    sanitized
                ));
            }

            output.push_str(&format!(
                "        // pre: {:?}\n",
                txn.contract.pre_condition
            ));

            for stmt in &txn.body {
                self.statement_to_rust(&mut output, stmt);
            }

            output.push_str(&format!(
                "        // post: {:?}\n",
                txn.contract.post_condition
            ));
            output.push_str("        true\n");
            output.push_str("    }\n\n");
        }

        output.push_str("}\n\n");

        for item in &program.items {
            if let TopLevel::Definition(defn) = item {
                let params: Vec<String> = defn.parameters.iter()
                    .map(|(n, t)| format!("{}: {}", n, Self::get_rust_type(t)))
                    .collect();
                let return_type = match &defn.output_type {
                    Some(ot) => {
                        let types: Vec<String> = ot.all_types().iter().map(|t| Self::get_rust_type(t)).collect();
                        if types.len() == 1 { types[0].clone() } else { format!("({})", types.join(", ")) }
                    }
                    None => "()".to_string(),
                };
                let param_str = if params.is_empty() {
                    "&self".to_string()
                } else {
                    format!("&self, {}", params.join(", "))
                };
                output.push_str(&format!(
                    "    pub fn {}({}) -> {} {{\n",
                    defn.name, param_str, return_type
                ));
                for stmt in &defn.body {
                    self.statement_to_rust(&mut output, stmt);
                }
                output.push_str("    }\n\n");
            }
        }

        output.push_str("fn main() {\n");
        output.push_str("    println!(\"Brief kernel starting\\n\");\n");
        output.push_str("    let mut state = State::default();\n");

        if let Some((txn_name, _)) = self.collect_transactions(program).first() {
            output.push_str(&format!("    state.{}();\n", Self::sanitize_name(txn_name)));
        }

        output.push_str("    println!(\"Brief kernel done\\n\");\n");
        output.push_str("}\n");

        output
    }

    /// Intent: Collect signal declarations from the program and assign indices.
    fn collect_signals(&mut self, program: &Program) {
        for item in &program.items {
            if let TopLevel::StateDecl(decl) = item {
                self.signal_map.insert(decl.name.clone(), self.signal_counter);
                self.signal_counter += 1;
            }
        }
    }

    /// Intent: Collect state variable declarations from the program.
    fn collect_state_declarations(&self, program: &Program) -> Vec<(String, Type)> {
        let mut decls = Vec::new();
        for item in &program.items {
            if let TopLevel::StateDecl(decl) = item {
                decls.push((decl.name.clone(), decl.ty.clone()));
            }
        }
        decls
    }

    /// Intent: Return an empty list of transaction names (placeholder).
    fn txn_names(&self) -> Vec<String> {
        vec![]
    }

    /// Intent: Collect all transaction definitions from the program.
    fn collect_transactions(&self, program: &Program) -> Vec<(String, crate::ast::Transaction)> {
        let mut txns = Vec::new();
        for item in &program.items {
            if let TopLevel::Transaction(txn) = item {
                txns.push((txn.name.clone(), txn.clone()));
            }
        }
        txns
    }

    /// Intent: Convert a Brief statement to Rust code for the generated State impl.
    fn statement_to_rust(&self, output: &mut String, stmt: &Statement) {
        match stmt {
            Statement::Assignment { lhs, expr, .. } => {
                let name = match lhs {
                    Expr::Identifier(n) => {
                        let n = n.clone();
                        self.mark_guard_dirty(output, &n);
                        n
                    }
                    Expr::OwnedRef(n) => format!("self.{}", n),
                    Expr::FieldAccess(obj, field) => {
                        format!("{}.{}", self.expr_to_rust_no_self(obj), field)
                    }
                    _ => return,
                };
                let expr_code = self.expr_to_rust(expr);
                output.push_str(&format!("        {} = {};\n", name, expr_code));
            }
            Statement::Let { name, ty, expr, address_expr, .. } => {
                if let Some(addr_expr) = address_expr {
                    let addr_code = self.expr_to_rust(addr_expr);
                    output.push_str(&format!("        let {}: *const u32 = {} as *const u32;\n", name, addr_code));
                } else if let Some(e) = expr {
                    let expr_code = self.expr_to_rust(e);
                    if let Some(t) = ty {
                        let rust_ty = Self::get_rust_type(t);
                        output.push_str(&format!("        let {}: {} = {};\n", name, rust_ty, expr_code));
                    } else {
                        output.push_str(&format!("        let {} = {};\n", name, expr_code));
                    }
                } else if let Some(t) = ty {
                    let rust_ty = Self::get_rust_type(t);
                    let default = Self::get_default_value(t);
                    output.push_str(&format!("        let {}: {} = {};\n", name, rust_ty, default));
                }
            }
            Statement::Unification { name, pattern, expr } => {
                let expr_code = self.expr_to_rust(expr);
                output.push_str(&format!("        // uni {}({}) = {}\n", name, pattern, expr_code));
                output.push_str(&format!("        if let {}({}) = {} {{\n", name, pattern, expr_code));
                output.push_str("        }\n");
            }
            Statement::InlineAsm { asm_string, clobbers, .. } => {
                let clobber_list = if clobbers.is_empty() {
                    String::new()
                } else {
                    clobbers.iter()
                        .map(|c| format!("\"{}\"", c))
                        .collect::<Vec<_>>()
                        .join(", ")
                };

                if clobbers.is_empty() {
                    output.push_str(&format!("        // asm: {}\n", asm_string));
                    output.push_str("        // Note: For nightly Rust with #![feature(asm)], use:\n");
                    output.push_str("        // unsafe { asm!(\"wfi\"); }\n");
                } else {
                    output.push_str(&format!("        // asm: {} (clobbers: {})\n", asm_string, clobber_list));
                    output.push_str("        // Inline asm template:\n");
                    output.push_str(&format!(
                        "        // unsafe {{ asm!(\"{}\" : : : {}); }}\n",
                        asm_string, clobber_list
                    ));
                }
            }
            Statement::Term { values, .. } => {
                let cleanup = std::mem::take(&mut *self.pending_cleanup.borrow_mut());
                for stmt in &cleanup {
                    self.statement_to_rust(output, stmt);
                }
                if values.is_empty() {
                    output.push_str("        return;\n");
                } else if values.len() == 1 {
                    if let Some(v) = &values[0] {
                        let expr_code = self.expr_to_rust(v);
                        output.push_str(&format!("        return {};\n", expr_code));
                    } else {
                        output.push_str("        return;\n");
                    }
                } else {
                    let vals: Vec<String> = values.iter().map(|v| {
                        match v {
                            Some(e) => self.expr_to_rust(e),
                            None => "()".to_string(),
                        }
                    }).collect();
                    output.push_str(&format!("        return ({});\n", vals.join(", ")));
                }
            }
            Statement::Escape(value) => {
                if let Some(v) = value {
                    let expr_code = self.expr_to_rust(v);
                    output.push_str(&format!("        return {};\n", expr_code));
                } else {
                    output.push_str("        return;\n");
                }
            }
            Statement::Expression(expr) => {
                let expr_code = self.expr_to_rust(expr);
                output.push_str(&format!("        {};\n", expr_code));
            }
            Statement::Guarded { condition, statements } => {
                let cond_code = self.expr_to_rust(condition);
                output.push_str(&format!("        if {} {{\n", cond_code));
                for s in statements {
                    self.statement_to_rust(output, s);
                }
                output.push_str("        }\n");
            }
            Statement::LocalTrigger { name, ty, expr, .. } => {
                let _ty_str = match ty {
                    Type::Int => "i64",
                    Type::UInt => "u64",
                    Type::Float => "f64",
                    Type::Bool => "bool",
                    Type::String => "String",
                    _ => "i64",
                };
                if let Some(e) = expr {
                    let expr_code = self.expr_to_rust(e);
                    output.push_str(&format!("        // trg! {}: await {}\n", name, expr_code));
                } else {
                    output.push_str(&format!("        // trg! {}: await external event\n", name));
                }
            }
            Statement::Alka(block) => {
                for line in block.content.lines() {
                    output.push_str(&format!("        {}\n", line));
                }
            }
            Statement::OnExit { body, .. } => {
                self.pending_cleanup.borrow_mut().extend(body.iter().cloned());
                output.push_str("        // #on_exit cleanup registered\n");
            }
            _ => {
                output.push_str("        // statement type not implemented\n");
            }
        }
    }

    /// Intent: Convert a Brief expression to Rust code with self access for state.
    fn expr_to_rust(&self, expr: &Expr) -> String {
        match expr {
            Expr::Integer(n) => n.to_string(),
            Expr::Float(f) => f.to_string(),
            Expr::Bool(b) => b.to_string(),
            Expr::String(s) => format!("\"{}\".to_string()", s),
            Expr::Char(c) => format!("'{}'", c),
            Expr::Identifier(n) => n.clone(),
            Expr::OwnedRef(n) => format!("self.{}", n),
            Expr::PriorState(n) => format!("self.{}", n),
            Expr::Add(a, b) => {
                if self.is_list_expr(a) && self.is_list_expr(b) {
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let len = std::cmp::min({}.len(), {}.len());\n            let mut result = Vec::with_capacity(len);\n            for i in 0..len {{\n                result.push({}[i] + {}[i]);\n            }}\n            result\n        }}", left, right, left, right)
                } else {
                    format!("({} + {})", self.expr_to_rust(a), self.expr_to_rust(b))
                }
            }
            Expr::Sub(a, b) => {
                if self.is_list_expr(a) && self.is_list_expr(b) {
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let len = std::cmp::min({}.len(), {}.len());\n            let mut result = Vec::with_capacity(len);\n            for i in 0..len {{\n                result.push({}[i] - {}[i]);\n            }}\n            result\n        }}", left, right, left, right)
                } else {
                    format!("({} - {})", self.expr_to_rust(a), self.expr_to_rust(b))
                }
            }
            Expr::Mul(a, b) => {
                if self.is_list_expr(a) && self.is_list_expr(b) {
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let len = std::cmp::min({}.len(), {}.len());\n            let mut result = Vec::with_capacity(len);\n            for i in 0..len {{\n                result.push({}[i] * {}[i]);\n            }}\n            result\n        }}", left, right, left, right)
                } else if self.is_list_expr(a) && !self.is_list_expr(b) {
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let mut result = {}.clone();\n            for i in 0..result.len() {{\n                result[i] = result[i] * {};\n            }}\n            result\n        }}", left, right)
                } else if !self.is_list_expr(a) && self.is_list_expr(b) {
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let mut result = {}.clone();\n            for i in 0..result.len() {{\n                result[i] = {} * result[i];\n            }}\n            result\n        }}", right, left)
                } else {
                    format!("({} * {})", self.expr_to_rust(a), self.expr_to_rust(b))
                }
            }
            Expr::Div(a, b) => {
                if self.is_list_expr(a) && self.is_list_expr(b) {
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let len = std::cmp::min({}.len(), {}.len());\n            let mut result = Vec::with_capacity(len);\n            for i in 0..len {{\n                result.push({}[i] / {}[i]);\n            }}\n            result\n        }}", left, right, left, right)
                } else {
                    format!("({} / {})", self.expr_to_rust(a), self.expr_to_rust(b))
                }
            }
            Expr::Mod(a, b) => format!("({} % {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Eq(a, b) => format!("({} == {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Ne(a, b) => format!("({} != {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Lt(a, b) => format!("({} < {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Le(a, b) => format!("({} <= {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Gt(a, b) => format!("({} > {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Ge(a, b) => format!("({} >= {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::And(a, b) => format!("({} && {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Or(a, b) => format!("({} || {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Not(a) => format!("!{}", self.expr_to_rust(a)),
            Expr::Neg(a) => format!("-{}", self.expr_to_rust(a)),
            Expr::BitNot(a) => format!("!{}", self.expr_to_rust(a)),
            Expr::BitAnd(a, b) => format!("({} & {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::BitOr(a, b) => format!("({} | {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::BitXor(a, b) => format!("({} ^ {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Shl(a, b) => format!("({} << {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Shr(a, b) => format!("({} >> {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::ListLen(inner) => format!("{}.len()", self.expr_to_rust(inner)),
            Expr::ListIndex(list, idx) => format!("{}[{}]", self.expr_to_rust(list), self.expr_to_rust(idx)),
            Expr::ListLiteral(elems) => {
                let items: Vec<String> = elems.iter().map(|e| self.expr_to_rust(e)).collect();
                format!("vec![{}]", items.join(", "))
            }
            Expr::FieldAccess(obj, field) => format!("{}.{}", self.expr_to_rust(obj), field),
            Expr::StructInstance(name, fields) => {
                let field_strs: Vec<String> = fields.iter()
                    .map(|(f, e)| format!("{}: {}", f, self.expr_to_rust(e)))
                    .collect();
                format!("{} {{ {} }}", name, field_strs.join(", "))
            }
            Expr::Call(name, args) => {
                let args_str: Vec<String> = args.iter().map(|e| self.expr_to_rust(e)).collect();
                format!("{}({})", name, args_str.join(", "))
            }
            Expr::Tuple(elems) => {
                let items: Vec<String> = elems.iter().map(|e| self.expr_to_rust(e)).collect();
                format!("({})", items.join(", "))
            }
            Expr::ForAll { var, expr } => {
                format!("/* forall {} */ {}", var, self.expr_to_rust(expr))
            }
            Expr::Exists { var, expr } => {
                format!("/* exists {} */ {}", var, self.expr_to_rust(expr))
            }
            Expr::Slice { value, start, end, .. } => {
                let val = self.expr_to_rust(value);
                match (start, end) {
                    (Some(s), Some(e)) => format!("{}[{}..{}]", val, self.expr_to_rust(s), self.expr_to_rust(e)),
                    (Some(s), None) => format!("{}[{}..]", val, self.expr_to_rust(s)),
                    (None, Some(e)) => format!("{}[..{}]", val, self.expr_to_rust(e)),
                    (None, None) => format!("{}", val),
                }
            }
            Expr::MultiSlice { value, coordinates, .. } => {
                let val = self.expr_to_rust(value);
                let coords: Vec<String> = coordinates.iter().map(|c| {
                    match c {
                        crate::ast::SliceCoordinate::Index(e) => self.expr_to_rust(e),
                        crate::ast::SliceCoordinate::Range { start, end } => {
                            match (start, end) {
                                (Some(s), Some(e)) => format!("{}..{}", self.expr_to_rust(s), self.expr_to_rust(e)),
                                (Some(s), None) => format!("{}..", self.expr_to_rust(s)),
                                (None, Some(e)) => format!("..{}", self.expr_to_rust(e)),
                                (None, None) => "..".to_string(),
                            }
                        }
                        crate::ast::SliceCoordinate::Named { name, coord } => {
                            format!("{}:{}", name, self.expr_to_rust_slice_coord(coord))
                        }
                    }
                }).collect();
                format!("{}[{}]", val, coords.join(", "))
            }
            Expr::PatternMatch { value, variant, fields } => {
                let fields_str = fields.join(", ");
                format!("match *{} {{ {}({}) => true, _ => false }}", self.expr_to_rust(value), variant, fields_str)
            }
            Expr::Block(stmts, last_expr) => {
                let mut block = "{\n".to_string();
                for stmt in stmts {
                    block.push_str("            ");
                    self.statement_to_rust(&mut block, stmt);
                }
                block.push_str(&format!("            {}\n        }}", self.expr_to_rust(last_expr)));
                block
            }
            Expr::TupleDestructure(names, expr) => {
                let names_str = names.join(", ");
                format!("let ({}) = {}", names_str, self.expr_to_rust(expr))
            }
            Expr::ObjectLiteral(fields) => {
                let field_strs: Vec<String> = fields.iter()
                    .map(|(f, e)| format!("{}: {}", f, self.expr_to_rust(e)))
                    .collect();
                format!("{{ {} }}", field_strs.join(", "))
            }
            _ => "0 /* expr not implemented */".to_string(),
        }
    }

    /// Intent: Convert a Brief expression to Rust code without self prefix for state.
    fn expr_to_rust_no_self(&self, expr: &Expr) -> String {
        match expr {
            Expr::Identifier(n) => n.clone(),
            Expr::FieldAccess(obj, field) => format!("{}.{}", self.expr_to_rust_no_self(obj), field),
            Expr::StructInstance(name, fields) => {
                let field_strs: Vec<String> = fields.iter()
                    .map(|(f, e)| format!("{}: {}", f, self.expr_to_rust_no_self(e)))
                    .collect();
                format!("{} {{ {} }}", name, field_strs.join(", "))
            }
            Expr::Call(name, args) => {
                let args_str: Vec<String> = args.iter().map(|e| self.expr_to_rust_no_self(e)).collect();
                format!("{}({})", name, args_str.join(", "))
            }
            Expr::Integer(n) => n.to_string(),
            Expr::Float(f) => f.to_string(),
            Expr::Bool(b) => b.to_string(),
            Expr::String(s) => format!("\"{}\"", s),
            Expr::ListLiteral(elems) => {
                let items: Vec<String> = elems.iter().map(|e| self.expr_to_rust_no_self(e)).collect();
                format!("vec![{}]", items.join(", "))
            }
            Expr::Tuple(elems) => {
                let items: Vec<String> = elems.iter().map(|e| self.expr_to_rust_no_self(e)).collect();
                format!("({})", items.join(", "))
            }
            Expr::Add(a, b) => format!("({} + {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Sub(a, b) => format!("({} - {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Mul(a, b) => format!("({} * {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Div(a, b) => format!("({} / {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Mod(a, b) => format!("({} % {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Eq(a, b) => format!("({} == {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Ne(a, b) => format!("({} != {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Lt(a, b) => format!("({} < {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Le(a, b) => format!("({} <= {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Gt(a, b) => format!("({} > {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Ge(a, b) => format!("({} >= {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::And(a, b) => format!("({} && {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Or(a, b) => format!("({} || {})", self.expr_to_rust_no_self(a), self.expr_to_rust_no_self(b)),
            Expr::Not(a) => format!("!{}", self.expr_to_rust_no_self(a)),
            Expr::Neg(a) => format!("-{}", self.expr_to_rust_no_self(a)),
            _ => self.expr_to_rust(expr),
        }
    }

    /// Intent: Check if an expression is a list or vector type.
    fn is_list_expr(&self, expr: &Expr) -> bool {
        match expr {
            Expr::Identifier(_) => true,
            Expr::FieldAccess(obj, _) => self.is_list_expr(obj),
            Expr::ListIndex(inner, _) => self.is_list_expr(inner),
            Expr::ListLiteral(_) => true,
            Expr::Slice { .. } | Expr::MultiSlice { .. } => true,
            _ => false,
        }
    }

    /// Intent: Convert a slice coordinate to Rust range/index syntax.
    fn expr_to_rust_slice_coord(&self, coord: &crate::ast::SliceCoordinate) -> String {
        match coord {
            crate::ast::SliceCoordinate::Index(e) => self.expr_to_rust(e),
            crate::ast::SliceCoordinate::Range { start, end } => {
                match (start, end) {
                    (Some(s), Some(e)) => format!("{}..{}", self.expr_to_rust(s), self.expr_to_rust(e)),
                    (Some(s), None) => format!("{}..", self.expr_to_rust(s)),
                    (None, Some(e)) => format!("..{}", self.expr_to_rust(e)),
                    (None, None) => "..".to_string(),
                }
            }
            crate::ast::SliceCoordinate::Named { name, coord } => {
                format!("{}:{}", name, self.expr_to_rust_slice_coord(coord))
            }
        }
    }

    /// Intent: Map a Brief type to its native Rust type string.
    fn get_rust_type(ty: &Type) -> String {
        match ty {
            Type::Int => "i64".to_string(),
            Type::UInt => "u64".to_string(),
            Type::Float => "f64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "String".to_string(),
            Type::Char => "char".to_string(),
            Type::Data => "Vec<u8>".to_string(),
            Type::Void => "()".to_string(),
            Type::Vector(inner, _dims) => {
                format!("Vec<{}>", Self::get_rust_type(inner))
            }
            Type::Applied(name, args) => {
                match name.as_str() {
                    "List" => {
                        let elem_type = args.first().map(|t| Self::get_rust_type(t)).unwrap_or_else(|| "i64".to_string());
                        format!("Vec<{}>", elem_type)
                    }
                    "Option" => {
                        let inner = args.first().map(|t| Self::get_rust_type(t)).unwrap_or_else(|| "i64".to_string());
                        format!("Option<{}>", inner)
                    }
                    "Result" => {
                        let ok = args.first().map(|t| Self::get_rust_type(t)).unwrap_or_else(|| "i64".to_string());
                        let err = args.get(1).map(|t| Self::get_rust_type(t)).unwrap_or_else(|| "String".to_string());
                        format!("Result<{}, {}>", ok, err)
                    }
                    "HashMap" => {
                        let k = args.first().map(|t| Self::get_rust_type(t)).unwrap_or_else(|| "String".to_string());
                        let v = args.get(1).map(|t| Self::get_rust_type(t)).unwrap_or_else(|| "i64".to_string());
                        format!("std::collections::HashMap<{}, {}>", k, v)
                    }
                    "HashSet" => {
                        let inner = args.first().map(|t| Self::get_rust_type(t)).unwrap_or_else(|| "i64".to_string());
                        format!("std::collections::HashSet<{}>", inner)
                    }
                    "Stack" => {
                        let inner = args.first().map(|t| Self::get_rust_type(t)).unwrap_or_else(|| "i64".to_string());
                        format!("Vec<{}>", inner)
                    }
                    "Queue" => {
                        let inner = args.first().map(|t| Self::get_rust_type(t)).unwrap_or_else(|| "i64".to_string());
                        format!("std::collections::VecDeque<{}>", inner)
                    }
                    _ => {
                        if args.is_empty() {
                            name.clone()
                        } else {
                            let args_str: Vec<String> = args.iter().map(|t| Self::get_rust_type(t)).collect();
                            format!("{}<{}>", name, args_str.join(", "))
                        }
                    }
                }
            }
            Type::Tuple(types) => {
                let inner: Vec<String> = types.iter().map(|t| Self::get_rust_type(t)).collect();
                format!("({})", inner.join(", "))
            }
            Type::Union(_types) => {
                "i64".to_string()
            }
            Type::Custom(name) => name.clone(),
            Type::Enum(name) => name.clone(),
            Type::Sig(name) => format!("Box<dyn Fn() -> {}>", name),
            Type::TypeVar(name) => name.clone(),
            Type::Generic(name, args) => {
                if args.is_empty() {
                    name.clone()
                } else {
                    let args_str: Vec<String> = args.iter().map(|t| Self::get_rust_type(t)).collect();
                    format!("{}<{}>", name, args_str.join(", "))
                }
            }
            Type::ContractBound(inner, _) => Self::get_rust_type(inner),
            Type::Constrained(inner, _) => Self::get_rust_type(inner),
        }
    }

    /// Intent: Get the default initialization value for a Brief type in Rust.
    fn get_default_value(ty: &Type) -> String {
        match ty {
            Type::Int => "0".to_string(),
            Type::UInt => "0".to_string(),
            Type::Float => "0.0".to_string(),
            Type::Bool => "false".to_string(),
            Type::String => "String::new()".to_string(),
            Type::Char => "'\\0'".to_string(),
            Type::Data => "Vec::new()".to_string(),
            Type::Void => "()".to_string(),
            Type::Vector(_, _) => "Vec::new()".to_string(),
            Type::Applied(name, _) if name == "List" => "Vec::new()".to_string(),
            Type::Applied(name, args) if name == "Option" => {
                let inner = args.first().map(|t| Self::get_default_value(t)).unwrap_or_else(|| "0".to_string());
                format!("Some({})", inner)
            }
            Type::Applied(name, _) if name == "Result" => "Ok(0)".to_string(),
            Type::Applied(name, _) if name == "HashMap" => "std::collections::HashMap::new()".to_string(),
            Type::Applied(name, _) if name == "HashSet" => "std::collections::HashSet::new()".to_string(),
            Type::Tuple(types) => {
                let defaults: Vec<String> = types.iter().map(|t| Self::get_default_value(t)).collect();
                format!("({})", defaults.join(", "))
            }
            Type::Custom(_) => "Default::default()".to_string(),
            _ => "0".to_string(),
        }
    }

    /// Intent: Collect identifier names from an expression.
    fn collect_expr_ids(expr: &Expr, ids: &mut HashSet<String>) {
        match expr {
            Expr::Identifier(n) | Expr::OwnedRef(n) | Expr::PriorState(n) => {
                ids.insert(n.clone());
            }
            Expr::Add(a, b) | Expr::Sub(a, b) | Expr::Mul(a, b) | Expr::Div(a, b)
            | Expr::Eq(a, b) | Expr::Ne(a, b) | Expr::Lt(a, b) | Expr::Le(a, b)
            | Expr::Gt(a, b) | Expr::Ge(a, b) | Expr::And(a, b) | Expr::Or(a, b)
            | Expr::BitAnd(a, b) | Expr::BitOr(a, b) | Expr::BitXor(a, b)
            | Expr::Shl(a, b) | Expr::Shr(a, b) | Expr::Mod(a, b) => {
                Self::collect_expr_ids(a, ids);
                Self::collect_expr_ids(b, ids);
            }
            Expr::Not(a) | Expr::Neg(a) | Expr::BitNot(a) => Self::collect_expr_ids(a, ids),
            Expr::Call(_, args) => {
                for arg in args {
                    Self::collect_expr_ids(arg, ids);
                }
            }
            _ => {}
        }
    }

    /// Intent: Mark dirty flags for guards that depend on the given state variable.
    fn mark_guard_dirty(&self, output: &mut String, var_name: &str) {
        if !self.enable_guard_cache {
            return;
        }
        if let Some(guards) = self.guard_tracker.var_to_guards.get(var_name) {
            for guard_name in guards {
                output.push_str(&format!(
                    "        self.{}_dirty = true;\n",
                    Self::sanitize_name(guard_name)
                ));
            }
        }
    }

    /// Intent: Sanitize a Brief identifier for use as a Rust name (replace hyphens with underscores).
    fn sanitize_name(name: &str) -> String {
        name.replace('-', "_")
    }
}