// Copyright 2026 Randy Smits-Schreuder Goedheijt
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use crate::ast::{BitRange, Expr, Program, Statement, TopLevel, Type};
use std::collections::HashMap;

pub struct RustBackend {
    spec: Option<crate::target_spec::TargetSpec>,
    signal_counter: usize,
    txn_counter: usize,
    signal_map: HashMap<String, usize>,
}

impl RustBackend {
    pub fn new() -> Self {
        Self {
            spec: None,
            signal_counter: 0,
            txn_counter: 0,
            signal_map: HashMap::new(),
        }
    }

    pub fn with_spec(mut self, spec: crate::target_spec::TargetSpec) -> Self {
        self.spec = Some(spec);
        self
    }

    pub fn generate(&mut self, program: &Program) -> String {
        self.collect_signals(program);

        let mut output = String::new();

        output.push_str("// Native Rust application - generated by Brief\n");
        let target_label = self.spec.as_ref()
            .and_then(|s| s.codegen.as_ref())
            .map(|s| s.entry_point.style.as_str())
            .unwrap_or("Desktop/Embedded Linux (std)");
        output.push_str(&format!("// Target: {}\n\n", target_label));

        if let Some(spec) = &self.spec {
            if let Some(cg) = &spec.codegen {
                if let Some(header) = &cg.templates.header {
                    output.push_str(header);
                    output.push_str("\n\n");
                }
            }
        } else {
            output.push_str("use std::fmt;\n\n");
        }

        let state_decls = self.collect_state_declarations(program);

        output.push_str("#[derive(Debug, Clone)]\n");
        output.push_str("pub struct State {\n");
        for (name, ty) in &state_decls {
            let rust_type = Self::get_rust_type(ty);
            output.push_str(&format!("    pub {}: {},\n", name, rust_type));
        }
        output.push_str("}\n\n");

        output.push_str("impl Default for State {\n");
        output.push_str("    fn default() -> Self {\n");
        output.push_str("        Self {\n");
        for (name, ty) in &state_decls {
            let default_val = Self::get_default_value(ty);
            output.push_str(&format!("            {}: {},\n", name, default_val));
        }
        output.push_str("        }\n");
        output.push_str("    }\n");
        output.push_str("}\n\n");

        output.push_str("impl State {\n");

        for (txn_name, txn) in self.collect_transactions(program) {
            output.push_str(&format!(
                "    pub fn {}(&mut self) -> bool {{\n",
                Self::sanitize_name(&txn.name)
            ));
            output.push_str(&format!(
                "        // pre: {:?}\n",
                txn.contract.pre_condition
            ));

            for stmt in &txn.body {
                self.statement_to_rust(&mut output, stmt);
            }

            output.push_str(&format!(
                "        // post: {:?}\n",
                txn.contract.post_condition
            ));
            output.push_str("        true\n");
            output.push_str("    }\n\n");
        }

        output.push_str("}\n\n");

        output.push_str("fn main() {\n");
        output.push_str("    println!(\"Brief kernel starting\\n\");\n");
        output.push_str("    let mut state = State::default();\n");

        if let Some((txn_name, _)) = self.collect_transactions(program).first() {
            output.push_str(&format!("    state.{}();\n", Self::sanitize_name(txn_name)));
        }

        output.push_str("    println!(\"Brief kernel done\\n\");\n");
        output.push_str("}\n");

        output
    }

    fn collect_signals(&mut self, program: &Program) {
        for item in &program.items {
            if let TopLevel::StateDecl(decl) = item {
                self.signal_map.insert(decl.name.clone(), self.signal_counter);
                self.signal_counter += 1;
            }
        }
    }

    fn collect_state_declarations(&self, program: &Program) -> Vec<(String, Type)> {
        let mut decls = Vec::new();
        for item in &program.items {
            if let TopLevel::StateDecl(decl) = item {
                decls.push((decl.name.clone(), decl.ty.clone()));
            }
        }
        decls
    }

    fn txn_names(&self) -> Vec<String> {
        vec![]
    }

    fn collect_transactions(&self, program: &Program) -> Vec<(String, crate::ast::Transaction)> {
        let mut txns = Vec::new();
        for item in &program.items {
            if let TopLevel::Transaction(txn) = item {
                txns.push((txn.name.clone(), txn.clone()));
            }
        }
        txns
    }

    fn statement_to_rust(&self, output: &mut String, stmt: &Statement) {
        match stmt {
            Statement::Assignment { lhs, expr, .. } => {
                let name = match lhs {
                    Expr::Identifier(n) | Expr::OwnedRef(n) => n.clone(),
                    _ => return,
                };
                let expr_code = self.expr_to_rust(expr);
                output.push_str(&format!("        self.{} = {};\n", name, expr_code));
            }
            Statement::Let { name, expr, .. } => {
                if let Some(e) = expr {
                    let expr_code = self.expr_to_rust(e);
                    output.push_str(&format!("        let mut {} = {};\n", name, expr_code));
                }
            }
            Statement::InlineAsm { asm_string, clobbers, .. } => {
                let clobber_list = if clobbers.is_empty() {
                    String::new()
                } else {
                    clobbers.iter()
                        .map(|c| format!("\"{}\"", c))
                        .collect::<Vec<_>>()
                        .join(", ")
                };

                if clobbers.is_empty() {
                    output.push_str(&format!("        // asm: {}\n", asm_string));
                    output.push_str("        // Note: For nightly Rust with #![feature(asm)], use:\n");
                    output.push_str("        // unsafe { asm!(\"wfi\"); }\n");
                } else {
                    output.push_str(&format!("        // asm: {} (clobbers: {})\n", asm_string, clobber_list));
                    output.push_str("        // Inline asm template:\n");
                    output.push_str(&format!(
                        "        // unsafe {{ asm!(\"{}\" : : : {}); }}\n",
                        asm_string, clobber_list
                    ));
                }
            }
            Statement::Term(_) => {
                output.push_str("        // transaction complete\n");
            }
            Statement::Expression(expr) => {
                let expr_code = self.expr_to_rust(expr);
                output.push_str(&format!("        {};\n", expr_code));
            }
            Statement::Escape(_) => {
                output.push_str("        return false; // transaction escaped\n");
            }
            Statement::Guarded { condition, statements } => {
                output.push_str("        // [guard] not fully implemented in native backend\n");
                for s in statements {
                    self.statement_to_rust(output, s);
                }
            }
            Statement::LocalTrigger { name, ty, expr, .. } => {
                // Local trigger: async wait point inside transaction
                let _ty_str = match ty {
                    Type::Int => "i64",
                    Type::UInt => "u64",
                    Type::Float => "f64",
                    Type::Bool => "bool",
                    Type::String => "String",
                    _ => "i64",
                };
                if let Some(e) = expr {
                    let expr_code = self.expr_to_rust(e);
                    output.push_str(&format!("        // trg! {}: await {}\n", name, expr_code));
                } else {
                    output.push_str(&format!("        // trg! {}: await external event\n", name));
                }
                // TODO: Full async yield/await semantics with rollback support
            }
            _ => {
                output.push_str("        // statement type not implemented\n");
            }
        }
    }

    fn expr_to_rust(&self, expr: &Expr) -> String {
        match expr {
            Expr::Integer(n) => n.to_string(),
            Expr::Float(f) => f.to_string(),
            Expr::Bool(b) => b.to_string(),
            Expr::String(s) => format!("\"{}\".to_string()", s),
            Expr::Identifier(n) => format!("self.{}", n),
            Expr::OwnedRef(n) => format!("self.{}", n),
            Expr::PriorState(n) => format!("self.{}", n),
            Expr::Add(a, b) => {
                // Check for List SIMD addition
                if self.is_list_expr(a) && self.is_list_expr(b) {
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let len = std::cmp::min({}.len(), {}.len());\n            let mut result = Vec::with_capacity(len);\n            for i in 0..len {{\n                result.push({}[i] + {}[i]);\n            }}\n            result\n        }}", left, right, left, right)
                } else {
                    format!("({} + {})", self.expr_to_rust(a), self.expr_to_rust(b))
                }
            }
            Expr::Sub(a, b) => {
                if self.is_list_expr(a) && self.is_list_expr(b) {
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let len = std::cmp::min({}.len(), {}.len());\n            let mut result = Vec::with_capacity(len);\n            for i in 0..len {{\n                result.push({}[i] - {}[i]);\n            }}\n            result\n        }}", left, right, left, right)
                } else {
                    format!("({} - {})", self.expr_to_rust(a), self.expr_to_rust(b))
                }
            }
            Expr::Mul(a, b) => {
                if self.is_list_expr(a) && self.is_list_expr(b) {
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let len = std::cmp::min({}.len(), {}.len());\n            let mut result = Vec::with_capacity(len);\n            for i in 0..len {{\n                result.push({}[i] * {}[i]);\n            }}\n            result\n        }}", left, right, left, right)
                } else if self.is_list_expr(a) && !self.is_list_expr(b) {
                    // Scalar broadcast: list * scalar
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let mut result = {}.clone();\n            for i in 0..result.len() {{\n                result[i] = result[i] * {};\n            }}\n            result\n        }}", left, right)
                } else if !self.is_list_expr(a) && self.is_list_expr(b) {
                    // Scalar broadcast: scalar * list
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let mut result = {}.clone();\n            for i in 0..result.len() {{\n                result[i] = {} * result[i];\n            }}\n            result\n        }}", right, left)
                } else {
                    format!("({} * {})", self.expr_to_rust(a), self.expr_to_rust(b))
                }
            }
            Expr::Div(a, b) => {
                if self.is_list_expr(a) && self.is_list_expr(b) {
                    let left = self.expr_to_rust(a);
                    let right = self.expr_to_rust(b);
                    format!("{{\n            let len = std::cmp::min({}.len(), {}.len());\n            let mut result = Vec::with_capacity(len);\n            for i in 0..len {{\n                result.push({}[i] / {}[i]);\n            }}\n            result\n        }}", left, right, left, right)
                } else {
                    format!("({} / {})", self.expr_to_rust(a), self.expr_to_rust(b))
                }
            }
            Expr::Eq(a, b) => format!("({} == {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Ne(a, b) => format!("({} != {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Lt(a, b) => format!("({} < {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Le(a, b) => format!("({} <= {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Gt(a, b) => format!("({} > {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Ge(a, b) => format!("({} >= {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::And(a, b) => format!("({} && {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Or(a, b) => format!("({} || {})", self.expr_to_rust(a), self.expr_to_rust(b)),
            Expr::Not(a) => format!("!{}", self.expr_to_rust(a)),
            Expr::Neg(a) => format!("-{}", self.expr_to_rust(a)),
            Expr::ListLen(inner) => {
                format!("{}.len()", self.expr_to_rust(inner))
            }
            Expr::ListIndex(list, idx) => {
                format!("{}[{}]", self.expr_to_rust(list), self.expr_to_rust(idx))
            }
            Expr::ListLiteral(elems) => {
                let items: Vec<String> = elems.iter().map(|e| self.expr_to_rust(e)).collect();
                format!("vec![{}]", items.join(", "))
            }
            _ => "0 /* expr not implemented */".to_string(),
        }
    }

    fn is_list_expr(&self, expr: &Expr) -> bool {
        match expr {
            Expr::Identifier(_) => true,
            Expr::FieldAccess(obj, _) => self.is_list_expr(obj),
            Expr::ListIndex(inner, _) => self.is_list_expr(inner),
            Expr::ListLiteral(_) => true,
            Expr::Slice { .. } | Expr::MultiSlice { .. } => true,
            _ => false,
        }
    }

    fn get_rust_type(ty: &Type) -> String {
        match ty {
            Type::Int => "i32".to_string(),
            Type::UInt => "u32".to_string(),
            Type::Float => "f64".to_string(),
            Type::Bool => "bool".to_string(),
            Type::String => "String".to_string(),
            Type::Vector(inner, dims) => {
                // Calculate total size
                let total_size: usize = dims.iter().map(|d| match d {
                    crate::ast::Dimension::Anonymous(s) => *s,
                    crate::ast::Dimension::Named(_, s) => *s,
                }).product();
                // For Rust, use a flat array or Vec with capacity
                format!("Vec<{}>", Self::get_rust_type(inner))
            }
            Type::Applied(name, args) if name == "List" => {
                let elem_type = args.first().map(|t| Self::get_rust_type(t)).unwrap_or_else(|| "i32".to_string());
                format!("Vec<{}>", elem_type)
            }
            Type::Constrained(inner, _) => Self::get_rust_type(inner),
            _ => "i32".to_string(),
        }
    }

    fn get_default_value(ty: &Type) -> String {
        match ty {
            Type::Int => "0".to_string(),
            Type::UInt => "0".to_string(),
            Type::Float => "0.0".to_string(),
            Type::Bool => "false".to_string(),
            Type::String => "String::new()".to_string(),
            Type::Vector(_, _) => "Vec::new()".to_string(),
            Type::Applied(name, _) if name == "List" => "Vec::new()".to_string(),
            _ => "0".to_string(),
        }
    }

    fn sanitize_name(name: &str) -> String {
        name.replace('-', "_")
    }
}

