// Autogenerated by Briv Compiler — do not edit manually
use std::ffi::c_void;

#[repr(C)]
pub struct BrivState { _private: [u8; 0] }

extern "C" {
    pub fn __briv_init_state() -> *mut c_void;
    pub fn __glue_release(state: *mut c_void);
        pub fn add(a: i64, b: i64) -> i64;
    pub fn feature_hash(state: *mut std::ffi::c_void, count: i64, seed: i64) -> i64;
}
