/* C application - generated by Brief */
/* Target: main */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdlib.h>


typedef struct {
    int32_t counter;
} State;

static State *state = NULL;

void state_init(void) {
    state->counter = 0;
}

bool increment(void) {    /* pre: Lt(Identifier("counter"), Integer(10)) */
    state->counter = (state->counter + 1);
    /* transaction complete */
    /* post: Eq(Identifier("counter"), Add(PriorState("counter"), Integer(1))) */
    return true;
}

static void init_wrapper(void) {
    state = (State *)malloc(sizeof(State));
    state_init();
}

int main(void) {
    init_wrapper();
    return 0;
}
