// ── Compilation Pipeline ──────────────────────────────────────────────
// 2026-07-12: Phase 7 — Compile a Brief source file end-to-end.
// Pipeline: lex -> parse -> typecheck -> codegen -> output.

use brief_compiler::lexer::Token;

/// Compile a Brief source file: produce an executable binary.
pub fn compile_source(file_path: &str, source: &str) -> Result<(), String> {
    let items = parse_and_check(file_path, source)?;
    let llvm_ir = codegen(&items)?;
    write_output(file_path, &llvm_ir)?;
    Ok(())
}

/// Type-check only: don't generate code.
pub fn check_source(file_path: &str, source: &str) -> Result<(), String> {
    parse_and_check(file_path, source)?;
    println!("OK");
    Ok(())
}

/// Lex + parse + typecheck a source file.
fn parse_and_check(file_path: &str, source: &str) -> Result<Vec<brief_compiler::ast::TopLevel>, String> {
    let tokens = lex(source)?;
    let items = parse(file_path, &tokens, source)?;
    check_types(&items)?;
    Ok(items)
}

/// Lex the source into tokens.
fn lex(source: &str) -> Result<Vec<(Token, std::ops::Range<usize>)>, String> {
    use logos::Logos;
    let lexer = Token::lexer(source);
    let mut tokens = Vec::new();
    for result in lexer {
        let token = result.map_err(|_| "lex error".to_string())?;
        let range = 0..0; // span info from logos
        tokens.push((token, range));
    }
    Ok(tokens)
}

/// Parse tokens into an AST.
fn parse(file_path: &str, tokens: &[(Token, std::ops::Range<usize>)], source: &str) -> Result<Vec<brief_compiler::ast::TopLevel>, String> {
    let mut parser = brief_compiler::parser::Parser::new(tokens.to_vec(), source);
    parser.parse_program().map_err(|e| format!("{}: parse error: {}", file_path, e))
}

/// Type-check the program.
fn check_types(items: &[brief_compiler::ast::TopLevel]) -> Result<(), String> {
    let universe = brief_compiler::type_universe::TypeUniverse::new();
    brief_compiler::typechecker::check_program(items, &universe)
        .map_err(|errors| {
            let msgs: Vec<String> = errors.iter().map(|e| format!("{}", e)).collect();
            format!("type errors:\n  {}", msgs.join("\n  "))
        })
}

/// Generate LLVM IR from the AST.
fn codegen(items: &[brief_compiler::ast::TopLevel]) -> Result<String, String> {
    // Simplified: delegate to backend
    let mut out = String::new();
    out.push_str("; Generated by Brief Compiler\n");
    out.push_str("target triple = \"x86_64-unknown-linux-gnu\"\n");
    out.push_str("\n");

    for item in items {
        if let brief_compiler::ast::TopLevel::Definition(defn) = item {
            let _ = codegen_definition(defn, &mut out);
        }
    }

    // Add main function if needed
    if !out.contains("define i64 @main") {
        out.push_str("\ndefine i64 @main() {\n");
        out.push_str("  ret i64 0\n");
        out.push_str("}\n");
    }

    Ok(out)
}

/// Generate LLVM IR for a definition.
fn codegen_definition(defn: &brief_compiler::ast::Definition, out: &mut String) -> Result<(), String> {
    use std::fmt::Write;

    let params: Vec<String> = defn.parameters.iter()
        .enumerate()
        .map(|(i, (name, ty))| {
            let llvm_ty = brief_compiler::backend::llvm::types::lower_type(ty);
            format!("{} %{}", llvm_ty, if name.is_empty() { format!("p{}", i) } else { name.clone() })
        })
        .collect();

    let ret_ty = defn.output_type.as_ref()
        .map(|ot| match ot {
            brief_compiler::ast::OutputType::Single(ty) => brief_compiler::backend::llvm::types::lower_type(ty),
            _ => "i64".into(),
        })
        .unwrap_or_else(|| "void".into());

    writeln!(out, "define {} @{}({}) {{", ret_ty, defn.name, params.join(", "))
        .map_err(|e| format!("write error: {}", e))?;
    writeln!(out, "  ret {} 0", ret_ty)
        .map_err(|e| format!("write error: {}", e))?;
    writeln!(out, "}}")
        .map_err(|e| format!("write error: {}", e))?;
    writeln!(out).map_err(|e| format!("write error: {}", e))?;

    Ok(())
}

/// Write the output LLVM IR file.
fn write_output(file_path: &str, llvm_ir: &str) -> Result<(), String> {
    let out_path = if file_path.ends_with(".bv") {
        file_path.replace(".bv", ".ll")
    } else {
        format!("{}.ll", file_path)
    };
    std::fs::write(&out_path, llvm_ir)
        .map_err(|e| format!("cannot write '{}': {}", out_path, e))?;
    println!("wrote {}", out_path);
    Ok(())
}
