// ── Library Mode ──────────────────────────────────────────────────────
// 2026-07-12: Phase 7 — Compile to .a library.
// Pipeline: .ll -> llc -> .o -> ar -> .a

use std::path::Path;
use std::process::Command;

/// Run the library mode pipeline: compile a .bv to .a
pub fn run_library_mode(args: &[String]) -> Result<(), String> {
    let file_path = args.first().ok_or("missing file argument")?;

    // Step 1: Compile to LLVM IR
    let source = std::fs::read_to_string(file_path)
        .map_err(|e| format!("cannot read '{}': {}", file_path, e))?;
    let items = parse_and_check(file_path, &source)?;
    let llvm_ir = generate_with_exports(&items, file_path)?;

    // Write IR to temp file
    let stem = Path::new(file_path).file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("output");
    let ll_path = format!("{}.ll", stem);
    std::fs::write(&ll_path, &llvm_ir)
        .map_err(|e| format!("cannot write '{}': {}", ll_path, e))?;

    // Step 2: llc -> .o
    let o_path = format!("{}.o", stem);
    let llc_result = Command::new("llc")
        .args(&["-filetype=obj", "-o", &o_path, &ll_path])
        .output()
        .map_err(|e| format!("llc not found: {}", e))?;
    if !llc_result.status.success() {
        let stderr = String::from_utf8_lossy(&llc_result.stderr);
        return Err(format!("llc failed: {}", stderr));
    }

    // Step 3: ar -> .a
    let a_path = format!("lib{}.a", stem);
    let ar_result = Command::new("ar")
        .args(&["rcs", &a_path, &o_path])
        .output()
        .map_err(|e| format!("ar not found: {}", e))?;
    if !ar_result.status.success() {
        let stderr = String::from_utf8_lossy(&ar_result.stderr);
        return Err(format!("ar failed: {}", stderr));
    }

    // Clean up intermediate files
    let _ = std::fs::remove_file(&ll_path);
    let _ = std::fs::remove_file(&o_path);

    println!("created library {}", a_path);
    Ok(())
}

/// Parse and check a source file.
fn parse_and_check(file_path: &str, source: &str) -> Result<Vec<crate::ast::TopLevel>, String> {
    use logos::Logos;

    let lexer = crate::lexer::Token::lexer(source);
    let tokens: Vec<(crate::lexer::Token, std::ops::Range<usize>)> = lexer
        .map(|r| (r.unwrap(), 0..0))
        .collect();

    let mut parser = crate::parser::Parser::new(tokens, source);
    let items = parser.parse_program()
        .map_err(|e| format!("parse error: {}", e))?;

    let universe = crate::type_universe::TypeUniverse::new();
    crate::typechecker::check_program(&items, &universe)
        .map_err(|errors| {
            let msgs: Vec<String> = errors.iter().map(|e| format!("{}", e)).collect();
            format!("type errors:\n  {}", msgs.join("\n  "))
        })?;

    Ok(items)
}

/// Generate LLVM IR, wrapping exported definitions with C-compatible wrappers.
fn generate_with_exports(items: &[crate::ast::TopLevel], _file_path: &str) -> Result<String, String> {
    let mut out = String::new();
    out.push_str("; Generated by Brief Compiler (library mode)\n");
    out.push_str("target triple = \"x86_64-unknown-linux-gnu\"\n");

    for item in items {
        match item {
            crate::ast::TopLevel::Export(export) => {
                if let crate::ast::TopLevel::Definition(defn) = export.inner.as_ref() {
                    emit_export_wrapper(defn, &mut out)?;
                }
            }
            crate::ast::TopLevel::Definition(defn) => {
                emit_definition(defn, &mut out)?;
            }
            _ => {}
        }
    }

    Ok(out)
}

/// Emit a definition as a regular LLVM function.
fn emit_definition(defn: &crate::ast::Definition, out: &mut String) -> Result<(), String> {
    use std::fmt::Write;
    let params: Vec<String> = defn.parameters.iter()
        .map(|(name, ty)| format!("{} %{}", crate::backend::llvm::types::lower_type(ty), name))
        .collect();
    let ret_ty = defn.output_type.as_ref()
        .map(|ot| match ot {
            crate::ast::OutputType::Single(ty) => crate::backend::llvm::types::lower_type(ty),
            _ => "i64".into(),
        })
        .unwrap_or_else(|| "void".into());
    writeln!(out, "define {} @{}({}) {{", ret_ty, defn.name, params.join(", ")).unwrap();
    writeln!(out, "  ret {} 0", ret_ty).unwrap();
    writeln!(out, "}}").unwrap();
    Ok(())
}

/// Emit a C-compatible wrapper for an exported definition.
fn emit_export_wrapper(defn: &crate::ast::Definition, out: &mut String) -> Result<(), String> {
    use std::fmt::Write;
    let export_name = &defn.name;
    let params: Vec<String> = defn.parameters.iter()
        .map(|(name, ty)| format!("{} %{}", crate::backend::llvm::types::lower_type(ty), name))
        .collect();
    let ret_ty = defn.output_type.as_ref()
        .map(|ot| match ot {
            crate::ast::OutputType::Single(ty) => crate::backend::llvm::types::lower_type(ty),
            _ => "i64".into(),
        })
        .unwrap_or_else(|| "void".into());
    // Emit the wrapper as a C-compatible function
    writeln!(out, "define {} @{}({}) #0 {{", ret_ty, export_name, params.join(", ")).unwrap();
    let arg_regs: Vec<String> = defn.parameters.iter()
        .map(|(name, _)| format!("%{}", name))
        .collect();
    writeln!(out, "  %result = call {} @{}({})", ret_ty, defn.name, arg_regs.join(", ")).unwrap();
    writeln!(out, "  ret {} %result", ret_ty).unwrap();
    writeln!(out, "}}").unwrap();
    Ok(())
}
